DAYS_OLD = 1
HOURS_OLD = 14

JOB_SEARCH_TERMS = '(junior OR trainee OR "entry level" OR pasante OR intern OR graduate OR grad OR asociado OR associate OR graduado OR becario) AND (IT OR sistemas OR developer OR desarrollador OR software OR engineer OR ingeniero OR programador OR technology OR tecnología OR tech OR informática OR computing OR computación OR redes OR network OR ciberseguridad OR cybersecurity OR security OR front OR frontend OR back OR backend OR "full stack" OR "full-stack" OR qa OR tester OR support OR sysadmin OR data OR datos OR cloud)'

FETCHER_CONFIG = {
    "GetOnBoardFetcher": {
        "base_url": "https://www.getonbrd.com/api/v0/categories/{category}/jobs",
        "per_page": 5,
        "page": 1,
        "timeout": 15,
        "seniority_ids": [1, 2],
        "categories": [
            "programacion",
            "desarrollo-mobile",
            "data-science-analytics",
            "sysadmin-devops-qa",
            "cybersecurity",
            "machine-learning-ai",
            "technical-support",
        ],
    },
    "JobSpyFetcher": {
        "site_name": ["indeed", "linkedin"],
        "location": "Buenos Aires, AR",
        "country_indeed": "Argentina",
        "results_wanted": 75,
        "hours_old": HOURS_OLD,
        "linkedin_fetch_description": True,
        "search_terms": JOB_SEARCH_TERMS,
    },
    "EducacionITFetcher": {
        "base_url": "https://empleos.educacionit.com/trabajos?nivel=junior",
        "timeout": 15,
    },
}


EXCLUDED_AREA_TERMS_TITLE = [
    # Finanzas
    "finanzas",
    "finance",
    "financiero",
    "financial",
    "contador",
    "contadora",
    "accountant",
    "contable",
    "accounting",
    "auditor",
    "auditora",
    "treasury",
    "tesoreria",
    "financial analyst",
    "analista financiero",
    "kyc",
    "compliance",
    "cumplimiento",
    "collector",
    "cobrador",
    "cobranzas",
    "procure to pay",
    "procurement",
    # Legal
    "abogado",
    "abogada",
    "lawyer",
    "attorney",
    "paralegal",
    "legal counsel",
    # RRHH y Admin
    "recursos humanos",
    "human resources",
    "rrhh",
    "hr",
    "hr specialist",
    "recruiter",
    "reclutador",
    "reclutadora",
    "talent acquisition",
    "asistente administrativo",
    "asistente administrativa",
    "secretaria",
    "secretario",
    "recepcionista",
    "auxiliar administrativo",
    "auxiliar administrativa",
    # Marketing & Ventas
    "marketing manager",
    "marketing specialist",
    "mkt",
    "paid media",
    "medios pagos",
    "performance marketing",
    "vendedor",
    "vendedora",
    "sales",
    "ventas",
    "account executive",
    "account manager",
    "comercial",
    "televentas",
    "social media manager",
    "community manager",
    # Operaciones y Logística
    "compras",
    "purchasing",
    "buyer",
    "comprador",
    "almacén",
    "warehouse",
    "logistics",
    "logistica",
    "supply chain",
    "cadena de suministro",
    "picker",
    "picking",
    # Servicio al Cliente
    "customer service",
    "servicio al cliente",
    "atención al cliente",
    "call center",
    "agente de soporte",
    # Creativo y Educativo
    "diseñador gráfico",
    "graphic designer",
    "copywriter",
    "redactor",
    "content writer",
    "profesor",
    "teacher",
    "docente",
    # Ingeniería no-IT / Salud
    "ingeniero industrial",
    "ingeniero mecánico",
    "ingeniero civil",
    "arquitecto civil",
    "civil engineer",
    "enfermero",
    "enfermera",
    "nurse",
    "médico",
    "médica",
    "doctor",
    "farmacéutico",
    "pharmacist",
    "clinical",
    "clínico",
    "microbiologia",
    # Otros
    "seguridad fisica",
]

TAGS_KEYWORDS = [
    # Roles
    "software engineer",
    "frontend",
    "backend",
    "fullstack",
    "mobile",
    "devops",
    "qa",
    "data analyst",
    "business analyst",
    "systems analyst",
    "web developer",
    "data science",
    "sysadmin",
    "security",
    # Lenguajes
    "python",
    "java",
    "javascript",
    "typescript",
    "c#",
    "golang",
    "ruby",
    "php",
    "kotlin",
    "swift",
    # Frontend
    "react",
    "vue",
    "angular",
    "svelte",
    "next.js",
    # Backend
    "node.js",
    "django",
    "flask",
    "spring",
    ".net",
    "express",
    "fastapi",
    "laravel",
    # Mobile
    "react native",
    "flutter",
    "android",
    "ios",
    # Databases
    "sql",
    "postgres",
    "mysql",
    "mongodb",
    "redis",
    # Cloud & Tools
    "aws",
    "azure",
    "gcp",
    "docker",
    "kubernetes",
    "terraform",
    "git",
    "ci/cd",
    # Data & ML
    "pandas",
    "power bi",
    "tableau",
    "spark",
    "machine learning",
    "tensorflow",
    "pytorch",
    # Other
    "api",
    "rest",
    "agile",
    "microservices",
]

LOG_UNFILTERED_JOBS = True
