FETCHER_CONFIG = {
    "GetOnBoardFetcher": {
        "base_url": "https://www.getonbrd.com/api/v0/categories/{category}/jobs",
        "per_page": 10,
        "page": 1,
        "timeout": 15,
        "hours_old": 24,
        "seniority_ids": [1, 2],
        "categories": [
            "programacion",
            "desarrollo-mobile",
            "data-science-analytics",
            "sysadmin-devops-qa",
            "cybersecurity",
            "machine-learning-ai",
            "technical-support",
        ],
    },
    "JobSpyFetcher": {
        "site_name": ["indeed", "linkedin"],
        "location": "Buenos Aires, AR",
        "country_indeed": "Argentina",
        "results_wanted": 75,
        "hours_old": 24,
        "linkedin_fetch_description": True,
        "search_terms": '(junior OR trainee OR "entry level" OR pasante OR intern OR graduate OR grad OR asociado OR associate OR graduado OR becario) AND (IT OR sistemas OR developer OR desarrollador OR software OR engineer OR programador OR ingeniero OR technology OR tecnología OR tech OR informática OR computing OR computación OR redes OR network OR ciberseguridad OR cybersecurity OR security OR front OR frontend OR back OR backend OR "full stack" OR "full-stack")',
    },
    "EducacionITFetcher": {
        "base_url": "https://empleos.educacionit.com/trabajos?nivel=junior",
        "timeout": 15,
        "hours_old": 24,
    },
}

EXCLUDED_SENIORITYS = [
    "senior",
    "sr",
    "sr.",
    "ssr",
    "semi-senior",
    "semisenior",
    "lead",
    "líder",
    "lider",
    "manager",
    "director",
    "head",
    "jefe",
    "jefa",
    "chief",
    "gerente",
    "principal",
    "staff",
    "architect",
    "arquitecto",
    "coordinador",
    "coordinadora",
    "coordinator",
    "especialista",
    "specialist",
    "expert",
    "experto",
    "consultor",
    "consultant",
    "ii",
    "iii",
    "level 2",
    "level 3",
]

EXCLUDED_AREA_TERMS = [
    # Finance, Compliance, Collection, and Admin roles
    "finanzas",
    "finance",
    "contador",
    "contadora",
    "accountant",
    "contabilidad",
    "accounting",
    "auditor",
    "auditora",
    "treasury",
    "tesoreria",
    "financial analyst",
    "analista financiero",
    "kyc",
    "compliance",
    "cumplimiento",
    "collector",
    "cobrador",
    "cobranzas",
    "asistente administrativo",
    "asistente administrativa",
    "administrative assistant",
    "secretaria",
    "secretario",
    "secretary",
    "recepcionista",
    "receptionist",
    "auxiliar administrativo",
    "auxiliar administrativa",
    # HR roles
    "recursos humanos",
    "human resources",
    "rrhh",
    "hr",
    "hr specialist",
    "hr manager",
    "recruiter",
    "reclutador",
    "reclutadora",
    "talent acquisition",
    "adquisición de talento",
    "generalista de rrhh",
    # Marketing & Sales roles
    "marketing manager",
    "marketing specialist",
    "mkt",
    "paid media",
    "medios pagos",
    "performance marketing",
    "marketing de resultados",
    "vendedor",
    "vendedora",
    "sales",
    "ventas",
    "account executive",
    "account manager",
    "ejecutivo de ventas",
    "ejecutivo comercial",
    "comercial",
    "commercial",
    "televentas",
    "social media manager",
    "community manager",
    "gestor de redes",
    # Operations & Logistics roles
    "compras",
    "purchasing",
    "buyer",
    "comprador",
    "almacén",
    "warehouse",
    "logistics coordinator",
    "coordinador logistica",
    "supply chain analyst",
    "cadena de suministro",
    # Customer service roles
    "customer service representative",
    "representante servicio al cliente",
    "atención al cliente",
    "call center agent",
    "agente de soporte",
    "cliente",
    "customer",
    "servicio al cliente",
    # Creative roles
    "diseñador gráfico",
    "diseñadora gráfica",
    "graphic designer",
    "ilustrador",
    "ilustradora",
    "illustrator",
    "copywriter",
    "redactor",
    "redactora",
    "content writer",
    # Professional services & Healthcare/Science
    "abogado",
    "abogada",
    "lawyer",
    "attorney",
    "paralegal",
    "arquitecto civil",
    "arquitecta civil",
    "civil architect",
    "construction manager",
    "profesor",
    "profesora",
    "teacher",
    "docente",
    "instructor",
    "instructora",
    "tutor",
    "tutora",
    "enfermero",
    "enfermera",
    "nurse",
    "médico",
    "médica",
    "doctor",
    "doctora",
    "farmacéutico",
    "farmacéutica",
    "pharmacist",
    "técnico radiología",
    "clinical",
    "clínico",
    "research associate",
    "asociado de investigación",
    # Engineering roles
    "ingeniero industrial",
    "ingenieria industrial",
    "industrial engineer",
    "ingeniero mecánico",
    "ingenieria mecanica",
    "mechanical engineer",
    "ingeniero electrónico",
    "electronic engineer",
    "electricista",
    "ingeniero civil",
    "civil engineer",
]


EXCLUDED_EXPERIENCE_PHRASES = [
    # English
    "3 years",
    "4 years",
    "5 years",
    "6 years",
    "7 years",
    "3+ years",
    "4+ years",
    "5+ years",
    "6+ years",
    "3-5 years",
    "4-6 years",
    "5-7 years",
    "minimum 3 years",
    "minimum 4 years",
    "minimum 5 years",
    # Spanish
    "3 años",
    "4 años",
    "5 años",
    "6 años",
    "7 años",
    "minimo 3 años",
    "minimo 4 años",
    "minimo 5 años",
    "minimo 6 años",
    "mínimo 3 años",
    "mínimo 4 años",
    "mínimo 5 años",
    "mínimo 6 años",
    "3-5 años",
    "4-6 años",
    "5-7 años",
    "al menos 3 años",
    "al menos 4 años",
    "al menos 5 años",
]

TAGS_KEYWORDS = [
    # Roles (8)
    "frontend",
    "backend",
    "fullstack",
    "devops",
    "qa",
    "data analyst",
    "data science",
    "mobile",
    # Lenguajes principales (10)
    "python",
    "java",
    "javascript",
    "typescript",
    "golang",
    "c#",
    "c++",
    "ruby",
    "php",
    "kotlin",
    # Frontend (3)
    "react",
    "vue",
    "angular",
    # Backend (5)
    "node.js",
    "django",
    "spring",
    ".net",
    "express",
    # Mobile (2)
    "react native",
    "flutter",
    # Databases (4)
    "sql",
    "postgres",
    "mongodb",
    "redis",
    # Cloud (3)
    "aws",
    "azure",
    "docker",
    # Metodologías (3)
    "git",
    "agile",
    "api rest",
]
