POSITIVE_SENIORITY_TERMS = {
    "trainee",
    "junior",
    "jr",
    "pasantía",
    "pasante",
    "internship",
    "sin experiencia",
    "primer empleo",
    "entry level",
}

EXCLUDED_SENIORITYS = [
    "senior",
    "sr",
    "sr.",
    "ssr",
    "semi-senior",
    "semisenior",
    "lead",
    "líder",
    "lider",
    "tech lead",
    "manager",
    "director",
    "head",
    "jefe",
    "jefa",
    "chief",
    "gerente",
    "principal",
    "staff",
    "architect",
    "expert",
    "experto",
    "specialist",
    "especialista",
    "consultor",
    "consultant",
    " ii",
    " iii",
    " iv",
    "level 2",
    "level 3",
    "level 4",
]

EXCLUDED_AREA_TERMS_TITLE = [
    # Finanzas y Admin
    "finanzas",
    "finance",
    "financiero",
    "financial",
    "contador",
    "contable",
    "accounting",
    "treasury",
    "tesoreria",
    "kyc",
    "compliance",
    "cumplimiento",
    "collector",
    "cobranzas",
    "procurement",
    "credit",
    "reaseguros",
    "supplier",
    "convenios",
    "cuentas",
    # Legal
    "abogado",
    "lawyer",
    "attorney",
    "paralegal",
    "legal",
    # RRHH
    "recursos humanos",
    "human resources",
    "rrhh",
    "hr",
    "recruiter",
    "reclutador",
    "talent acquisition",
    # Admin y Asistencia
    "administrativo",
    "administrativa",
    "secretaria",
    "recepcionista",
    "auxiliar",
    # Marketing y Ventas
    "marketing",
    "mkt",
    "paid media",
    "performance marketing",
    "vendedor",
    "sales",
    "comercial",
    "televentas",
    "social media",
    "community manager",
    "marketplace",
    "catalog management",
    # Operaciones, Logística y Producción
    "compras",
    "purchasing",
    "buyer",
    "comprador",
    "almacén",
    "warehouse",
    "logistics",
    "logistica",
    "supply chain",
    "picker",
    "picking",
    "deposito",
    "tienda",
    "stockroom",
    "producción",
    "gomero",
    "camiones",
    "supervisor",
    # Servicio al Cliente
    "customer service",
    "atención al cliente",
    "call center",
    # Creativo y Educativo
    "diseñador gráfico",
    "graphic design",
    "copywriter",
    "redactor",
    "content",
    "profesor",
    "teacher",
    "docente",
    "editor",
    "audiovisual",
    "traductor",
    "interpreter",
    # Ingeniería no-IT y Salud
    "industrial",
    "mecánico",
    "civil",
    "enfermero",
    "nurse",
    "médico",
    "doctor",
    "farmacéutico",
    "pharmacist",
    "clinical",
    "clínico",
    "microbiologia",
    "instrumentation",
    "procesos",
    "energías renovables",
    "tierras",
    # Otros
    "seguridad fisica",
    "feria de empleo",
    "ctm",
]

EXCLUDED_EXPERIENCE_PHRASES = [
    "3 years",
    "4 years",
    "5 years",
    "6 years",
    "7 years",
    "3+ years",
    "4+ years",
    "5+ years",
    "6+ years",
    "3-5 years",
    "4-6 years",
    "5-7 years",
    "minimum 3 years",
    "minimum 4 years",
    "minimum 5 years",
    "3 años",
    "4 años",
    "5 años",
    "6 años",
    "7 años",
    "minimo 3 años",
    "minimo 4 años",
    "minimo 5 años",
    "mínimo 3 años",
    "mínimo 4 años",
    "mínimo 5 años",
    "3-5 años",
    "4-6 años",
    "5-7 años",
    "al menos 3 años",
    "al menos 4 años",
    "al menos 5 años",
]

TAGS_KEYWORDS = [
    "frontend",
    "backend",
    "fullstack",
    "mobile",
    "devops",
    "qa",
    "data analyst",
    "business analyst",
    "systems analyst",
    "web developer",
    "data science",
    "sysadmin",
    "python",
    "java",
    "javascript",
    "typescript",
    "c#",
    "golang",
    "ruby",
    "php",
    "kotlin",
    "swift",
    "react",
    "vue",
    "angular",
    "svelte",
    "next.js",
    "node.js",
    "django",
    "flask",
    "spring",
    ".net",
    "express",
    "fastapi",
    "laravel",
    "react native",
    "flutter",
    "android",
    "ios",
    "sql",
    "postgres",
    "mysql",
    "mongodb",
    "redis",
    "aws",
    "azure",
    "gcp",
    "docker",
    "kubernetes",
    "terraform",
    "git version control",
    "ci/cd",
    "pandas",
    "power bi",
    "tableau",
    "spark",
    "machine learning",
    "tensorflow",
    "pytorch",
    "api",
    "rest api",
    "agile",
    "microservices",
    "html",
    "css",
    "sass",
    "less",
    "linux",
    "windows",
    "macos",
    "bash",
    "powershell",
    "scrum",
]

REQUIRED_IT_SIGNALS = TAGS_KEYWORDS + [
    "developer",
    "desarrollador",
    "engineer",
    "ingeniero de software",
    "programmer",
    "programador",
    "analista de datos",
    "analista de sistemas",
    "analista de negocio",
    "technical support",
    "soporte técnico",
    "help desk",
    "pentester",
    "soc analyst",
    "network engineer",
    "software",
    "tech",
    "technology",
    "informática",
    "computing",
    "tecnología",
    "c++",
    "elasticsearch",
    "oracle",
    "jenkins",
    "gitlab",
    "ansible",
    "hadoop",
    "cisco",
    "firewall",
    "vpn",
    "business intelligence",
    "etl",
    "data warehouse",
    "cloud computing",
    "automation",
    "testing",
    "api gateway",
    "data modeling",
    "machine learning engineer",
    "data engineer",
    "web developer",
    "desarrollador web",
    "cybersecurity analyst",
    "analista de ciberseguridad",
    "analista funcional",
    "dev",
    "programador/a",
]
