MIN_SCORE = 60

MIN_YEARS_SENIORITY = 3

SENIOR_EXPERIENCE_PATTERNS = [
    r"(\d+)\s*a[ñn]os",
    r"(\d+)\s*years",
    r"(\d+)\+\s*a[ñn]os",
    r"(\d+)\+\s*years",
    r"m[íi]nimo\s*(\d+)\s*a[ñn]os",
    r"minimum\s*(\d+)\s*years",
    r"m[íi]nimo\s*(\d+)\s*years",
    r"al\s*menos\s*(\d+)\s*a[ñn]os",
    r"al\s*menos\s*(\d+)\s*years",
    r"at\s*least\s*(\d+)\s*years",
    r"(\d+)\s*-\s*\d+\s*a[ñn]os",
    r"(\d+)\s*-\s*\d+\s*years",
]


POSITIVE_SENIORITY_TERMS = {
    # Inglés
    "trainee",
    "junior",
    "jr",
    "jr.",
    "entry level",
    "entry-level",
    "internship",
    "intern",
    "graduate",
    "grad",
    "associate",
    "no experience",
    "first job",
    # Español
    "pasantía",
    "pasante",
    "sin experiencia",
    "primer empleo",
    "asociado",
    "graduado",
    "becario",
    "aprendiz",
}

EXCLUDED_SENIORITYS = [
    "senior",
    "sr",
    "sr.",
    "ssr",
    "semi-senior",
    "semisenior",
    "lead",
    "líder",
    "lider",
    "tech lead",
    "team lead",
    "manager",
    "director",
    "head",
    "jefe",
    "jefa",
    "chief",
    "gerente",
    "principal",
    "staff",
    "architect",
    "expert",
    "experto",
    "specialist",
    "especialista",
    "consultor",
    "consultant",
    " ii",
    " iii",
    " iv",
    "level 2",
    "level 3",
    "level 4",
    "pl",
]

EXCLUDED_AREA_TERMS_TITLE = [
    # Finanzas & Contabilidad
    "finanzas",
    "finance",
    "financiero",
    "financial",
    "contador",
    "contadora",
    "accountant",
    "contable",
    "accounting",
    "auditor",
    "auditora",
    "treasury",
    "tesoreria",
    "tesorero",
    "treasury analyst",
    "kyc",
    "aml",
    "cobranzas",
    "collector",
    "credit",
    "credito",
    "credit analyst",
    "reaseguros",
    "cuentas",
    "convenios",
    "procurement",
    "compras",
    "purchasing",
    "buyer",
    "comprador",
    "supplier",
    "controller financiero",
    "financial controller",
    "underwriter",
    "commodity",
    "commodities",
    "trading",
    "broker",
    "market analyst",
    "financial markets",
    "energy market",
    "oil & gas",
    "petroleum",
    # Legal
    "abogado",
    "abogada",
    "lawyer",
    "attorney",
    "paralegal",
    "legal counsel",
    # RRHH
    "recursos humanos",
    "human resources",
    "rrhh",
    "hr specialist",
    "hr manager",
    "recruiter",
    "reclutador",
    "reclutadora",
    "talent acquisition",
    # Admin & Asistencia
    "administrativo",
    "administrativa",
    "asistente administrativo",
    "asistente comercial",
    "asistente de ventas",
    "secretaria",
    "secretario",
    "recepcionista",
    "auxiliar administrativo",
    # Marketing & Ventas
    "marketing manager",
    "marketing specialist",
    "mkt specialist",
    "paid media",
    "performance marketing",
    "vendedor",
    "vendedora",
    "sales representative",
    "sales executive",
    "sales manager",
    "gerente de ventas",
    "account manager",
    "gerente de cuentas",
    "salesperson",
    "agente de ventas",
    "sales associate",
    "asociado de ventas",
    "business development representative",
    "representante de desarrollo de negocio",
    "inside sales",
    "ventas internas",
    "appointment setter",
    "generador de citas",
    "comercial",
    "ejecutivo comercial",
    "televentas",
    "social media manager",
    "community manager",
    "marketplace specialist",
    "catalog management",
    "business development",
    "growth",
    "account executive sales",
    "marketing strategist",
    "brand strategist",
    "growth strategist",
    "marketing lead",
    "marketing director",
    "chief marketing officer",
    # Operaciones & Logística
    "almacén",
    "warehouse",
    "logistics coordinator",
    "logistica",
    "supply chain analyst",
    "picker",
    "picking",
    "deposito",
    "stockroom",
    "tienda",
    "producción",
    "production",
    "supervisor de produccion",
    "gomero",
    "camiones",
    "truck driver",
    # Servicio al Cliente
    "customer service representative",
    "atención al cliente",
    "customer success",
    "customer support",
    "call center agent",
    "call center representative",
    # Creativo & Contenido
    "diseñador gráfico",
    "diseñadora gráfica",
    "graphic designer",
    "diseñador industrial",
    "industrial designer",
    "diseñador de modas",
    "fashion designer",
    "diseñador de interiores",
    "interior designer",
    "copywriter",
    "redactor",
    "redactora",
    "content writer",
    "content creator",
    "editor de contenido",
    "audiovisual",
    "video editor",
    "traductor",
    "translator",
    "interpreter",
    "english writer",
    "creative strategist",
    # Educación
    "profesor",
    "profesora",
    "teacher",
    "docente",
    "instructor",
    "tutor",
    # Ingeniería NO-Software
    "ingeniero industrial",
    "ingeniero mecánico",
    "ingeniero civil",
    "industrial engineer",
    "mechanical engineer",
    "civil engineer",
    "técnico electrónico",
    "instrumentation",
    "procesos industriales",
    "energías renovables",
    "ingeniero electrónico",
    "electronic engineer",
    "ingeniería electrónica",
    # Salud
    "enfermero",
    "enfermera",
    "nurse",
    "médico",
    "médica",
    "doctor",
    "doctora",
    "farmacéutico",
    "farmacéutica",
    "pharmacist",
    "clinical",
    "clínico",
    "microbiologia",
    "medical professional",
    "healthcare",
    "hospital",
    "clinic",
    "biotech",
    "biomedical",
    "clinical research",
    "medic",
    "health assistant",
    # Otros
    "seguridad fisica",
    "security guard",
    "land surveyor",
    "agente inmobiliario",
    "real estate",
    "property manager",
]

TAGS_KEYWORDS = {
    "Roles": [
        "frontend", "backend", "fullstack", "mobile", "devops", "qa", "tester",
        "data analyst", "data science", "data engineer", "sysadmin", "security",
        "support", "ux", "ui", "ux/ui", "product design"
    ],
    "Languages": [
        "python", "java", "javascript", "typescript", "c#", "golang", "ruby",
        "php", "kotlin", "swift", "sql"
    ],
    "Others": [
        "react", "vue", "angular", "next.js", "node.js", "django", "flask",
        "spring", ".net", "express", "fastapi", "laravel", "react native",
        "flutter", "pandas", "power bi", "tableau", "spark", "machine learning",
        "tensorflow", "figma", "sketch", "adobe xd", "aws", "azure", "gcp",
        "docker", "kubernetes", "terraform", "git", "ci/cd", "postgres",
        "mysql", "mongodb", "redis", "api", "rest api", "agile", "microservices"
    ]
}

WEAK_IT_SIGNALS = {
    "tech",
    "technology",
    "tecnología",
    "sistemas",
    "informática",
    "computing",
    "it",
    "analyst",
    "analista",
    "support",
    "soporte",
    "specialist",
    "especialista",
}

REQUIRED_IT_SIGNALS = [keyword for category in TAGS_KEYWORDS.values() for keyword in category] + [
    # Roles generales IT (SIN los términos ambiguos que están en WEAK)
    "developer",
    "desarrollador",
    "dev",
    "engineer",
    "ingeniero",
    "ingeniero de software",
    "programmer",
    "programador",
    "programador/a",
    # Desarrollo
    "web developer",
    "desarrollador web",
    "software developer",
    "software engineer",
    "full stack",
    "full-stack",
    # Data & Analytics
    "data analyst",
    "analista de datos",
    "data scientist",
    "científico de datos",
    "data engineer",
    "ingeniero de datos",
    "systems analyst",
    "analista de sistemas",
    "analista funcional",
    "business intelligence",
    "bi analyst",
    "bi developer",
    # Sysadmin & DevOps
    "sysadmin",
    "system administrator",
    "administrador de sistemas",
    "devops engineer",
    "devsecops",
    "site reliability engineer",
    "sre",
    "infrastructure engineer",
    "cloud engineer",
    "ingeniero cloud",
    # QA & Testing (CON CONTEXTO)
    "qa engineer",
    "quality assurance engineer",
    "qa analyst",
    "qa tester",
    "test automation engineer",
    "automation engineer",
    "quality engineer",
    # Seguridad (CON CONTEXTO)
    "security analyst",
    "analista de seguridad",
    "cybersecurity analyst",
    "analista de ciberseguridad",
    "security engineer",
    "ingeniero de seguridad",
    "pentester",
    "penetration tester",
    "soc analyst",
    "security operations",
    "infosec analyst",
    "it compliance",
    "security compliance",
    "compliance engineer",
    "sox compliance",
    "gdpr compliance",
    "iso 27001",
    "pci dss",
    # Machine Learning & AI
    "machine learning engineer",
    "ml engineer",
    "ai engineer",
    "artificial intelligence",
    "deep learning engineer",
    "mlops engineer",
    # Soporte Técnico (CON CONTEXTO)
    "technical support",
    "soporte técnico",
    "it support",
    "support engineer",
    "help desk",
    "service desk",
    "tech support specialist",
    # UX/UI Design
    "ux designer",
    "ui designer",
    "ux/ui designer",
    "user experience designer",
    "user interface designer",
    "product designer",
    "diseñador de producto",
    "diseñador ux",
    "diseñador ui",
    "diseñador ux/ui",
    "ux researcher",
    "ux research",
    "ui developer",
    "frontend designer",
    "interaction designer",
    "diseñador de interacción",
    "visual designer",
    "diseñador visual",
    "usability",
    "usabilidad",
    "prototyping",
    "prototipado",
    "wireframing",
    "wireframes",
    "user research",
    "investigación de usuarios",
    "invision",
    "zeplin",
    "framer",
    "design system",
    "sistema de diseño",
    # Redes
    "network engineer",
    "ingeniero de redes",
    "network administrator",
    "administrador de redes",
    "network analyst",
    "software",
    # Tecnologías específicas
    "c++",
    "c",
    "rust",
    "scala",
    "perl",
    "oracle",
    "sqlserver",
    "cassandra",
    "elasticsearch",
    "jenkins",
    "gitlab",
    "ansible",
    "puppet",
    "chef",
    "circleci",
    "travis",
    "github actions",
    "hadoop",
    "kafka",
    "airflow",
    "pytorch",
    "scikit-learn",
    "keras",
    "cisco",
    "firewall",
    "vpn",
    "ids",
    "ips",
    "html",
    "css",
    "sass",
    "less",
    "linux",
    "unix",
    "windows server",
    "bash",
    "powershell",
    # Conceptos
    "etl",
    "data warehouse",
    "data pipeline",
    "data modeling",
    "cloud computing",
    "automation",
    "testing",
    "api gateway",
    "graphql",
    "microservices architecture",
]

# Remove weak signals from required signals
REQUIRED_IT_SIGNALS = [s for s in REQUIRED_IT_SIGNALS if s not in WEAK_IT_SIGNALS]

STRONG_TECH_SIGNALS = {
    "python",
    "java",
    "javascript",
    "typescript",
    "react",
    "node.js",
    "aws",
    "docker",
    "sql",
    "kubernetes",
    "django",
    "spring",
    ".net",
    "vue",
    "angular",
    "figma",
    "sketch",
    "c++",
    "golang",
}

STRONG_ROLE_SIGNALS = {
    "developer",
    "desarrollador",
    "engineer",
    "ingeniero",
    "programmer",
    "programador",
    # Roles más específicos
    "software engineer",
    "ingeniero de software",
    "frontend developer",
    "desarrollador frontend",
    "backend developer",
    "desarrollador backend",
    "fullstack developer",
    "desarrollador fullstack",
    "data scientist",
    "científico de datos",
    "data engineer",
    "ingeniero de datos",
    # Roles de diseño
    "ux designer",
    "ui designer",
    "ux/ui designer",
    "product designer",
}

AMBIGUOUS_ROLES = {
    "analyst",
    "analista",
    "coordinator",
    "coordinador",
    "assistant",
    "asistente",
    "specialist",
    "especialista",
    "product owner",
    "product manager",
    "project manager",
    "scrum master",
    "agile coach",
}
