MIN_SCORE = 60
MIN_YEARS_SENIORITY = 3

SENIOR_EXPERIENCE_PATTERNS = [
    r"(\d+)\s*a[ñn]os",
    r"(\d+)\s*years",
    r"(\d+)\+\s*a[ñn]os",
    r"(\d+)\+\s*years",
    r"m[íi]nimo\s*(\d+)\s*a[ñn]os",
    r"minimum\s*(\d+)\s*years",
    r"al\s*menos\s*(\d+)\s*a[ñn]os",
    r"at\s*least\s*(\d+)\s*years",
    r"(\d+)\s*-\s*\d+\s*a[ñn]os",
    r"(\d+)\s*-\s*\d+\s*years",
]

POSITIVE_SENIORITY_TERMS = {
    # Inglés
    "trainee",
    "junior",
    "jr",
    "jr.",
    "entry level",
    "entry-level",
    "internship",
    "intern",
    "graduate",
    "grad",
    "no experience",
    "first job",
    "beginner",
    # Español
    "pasantía",
    "pasante",
    "sin experiencia",
    "primer empleo",
    "primer trabajo",
    "graduado",
    "recién graduado",
    "becario",
    "aprendiz",
    "inicial",
}

EXCLUDED_SENIORITYS = [
    # Senior levels
    "senior",
    "sr",
    "sr.",
    "ssr",
    "semi senior",
    "semi-senior",
    "semisenior",
    # Leadership
    "lead",
    "líder",
    "lider",
    "tech lead",
    "team lead",
    "squad lead",
    "chapter lead",
    # Management
    "manager",
    "director",
    "head",
    "jefe",
    "jefa",
    "chief",
    "gerente",
    "coordinador",
    "coordinator",
    "supervisor",
    # Advanced roles
    "principal",
    "staff",
    "architect",
    "arquiteto",
    "arquitecto",
    "expert",
    "experto",
    "consultor",
    "consultant",
    # Level indicators
    " ii",
    " iii",
    " iv",
    " v",
    "level 2",
    "level 3",
    "level 4",
    "nivel 2",
    "nivel 3",
    "nivel 4",
    "pl",
    "pleno",
    # Years indicators
    "3+",
    "4+",
    "5+",
    "+3",
    "+4",
    "+5",
]

EXCLUDED_AREA_TERMS_TITLE = [
    # Finanzas & Contabilidad
    "finanzas",
    "finance",
    "financiero",
    "financial",
    "contador",
    "contadora",
    "accountant",
    "contable",
    "accounting",
    "auditor",
    "auditora",
    "treasury",
    "tesoreria",
    "tesorero",
    "kyc",
    "aml",
    "cobranzas",
    "collector",
    "collections",
    "credit",
    "credito",
    "reaseguros",
    "cuentas por cobrar",
    "cuentas por pagar",
    "accounts payable",
    "accounts receivable",
    "convenios",
    "procurement",
    "compras",
    "purchasing",
    "buyer",
    "comprador",
    "supplier",
    "underwriter",
    "commodity",
    "commodities",
    "trading",
    "trader",
    "broker",
    "actuario",
    "actuary",
    # Regulatorio / Legal
    "asuntos regulatorios",
    "regulatory affairs",
    # Legal
    "abogado",
    "abogada",
    "lawyer",
    "attorney",
    "paralegal",
    "legal counsel",
    "compliance officer",
    "legal assistant",
    # RRHH
    "recursos humanos",
    "human resources",
    "rrhh",
    "hr",
    "recruiter",
    "reclutador",
    "reclutadora",
    "talent acquisition",
    "talent management",
    "people operations",
    "people partner",
    # Admin & Asistencia
    "administrativo",
    "administrativa",
    "asistente administrativo",
    "asistente comercial",
    "asistente de ventas",
    "asistente ejecutivo",
    "secretaria",
    "secretario",
    "recepcionista",
    "auxiliar administrativo",
    "office manager",
    # Marketing & Ventas
    "marketing manager",
    "marketing coordinator",
    "mkt",
    "paid media",
    "performance marketing",
    "vendedor",
    "vendedora",
    "sales representative",
    "sales executive",
    "sales manager",
    "gerente de ventas",
    "account manager",
    "gerente de cuentas",
    "salesperson",
    "agente de ventas",
    "sales associate",
    "business development representative",
    "bdr",
    "sdr",
    "inside sales",
    "ventas internas",
    "appointment setter",
    "generador de citas",
    "comercial",
    "ejecutivo comercial",
    "televentas",
    "social media manager",
    "community manager",
    "marketplace specialist",
    "catalog management",
    "brand manager",
    "product marketing",
    "growth hacker",
    # Operaciones & Logística
    "almacén",
    "warehouse",
    "logistics",
    "logistica",
    "supply chain",
    "picker",
    "picking",
    "deposito",
    "stockroom",
    "tienda",
    "producción",
    "production",
    "operario",
    "gomero",
    "camiones",
    "truck driver",
    "chofer",
    "driver",
    # Servicio al Cliente
    "customer service",
    "atención al cliente",
    "customer success",
    "customer support",
    "call center",
    "contact center",
    # Creativo & Contenido (NO incluir UX/UI aquí)
    "diseñador gráfico",
    "diseñadora gráfica",
    "graphic designer",
    "diseñador industrial",
    "industrial designer",
    "diseñador de modas",
    "fashion designer",
    "diseñador de interiores",
    "interior designer",
    "copywriter",
    "redactor",
    "redactora",
    "content writer",
    "content creator",
    "editor de contenido",
    "audiovisual",
    "video editor",
    "photographer",
    "fotógrafo",
    "traductor",
    "translator",
    "interpreter",
    "intérprete",
    # Educación
    "profesor",
    "profesora",
    "teacher",
    "docente",
    "instructor",
    "tutor",
    "capacitador",
    # Ingeniería NO-Software
    "ingeniero industrial",
    "ingeniero mecánico",
    "ingeniero civil",
    "ingeniero químico",
    "industrial engineer",
    "mechanical engineer",
    "civil engineer",
    "chemical engineer",
    "técnico electrónico",
    "instrumentation",
    "procesos industriales",
    "energías renovables",
    "oil & gas",
    "petroleum",
    "minería",
    "mining",
    # Salud
    "enfermero",
    "enfermera",
    "nurse",
    "médico",
    "médica",
    "doctor",
    "doctora",
    "farmacéutico",
    "farmacéutica",
    "pharmacist",
    "microbiologia",
    "healthcare",
    "hospital",
    "clinic",
    "clínico",
    "biomedical",
    "clinical research",
    "medical assistant",
    # Otros
    "seguridad fisica",
    "security guard",
    "vigilante",
    "land surveyor",
    "agente inmobiliario",
    "real estate",
    "property manager",
    "chef",
    "cocinero",
    "bartender",
    "camarero",
    "mesero",
]

TAGS_KEYWORDS = {
    "roles": [
        "frontend",
        "backend",
        "fullstack",
        "mobile",
        "devops",
        "qa",
        "data scientist",
        "data engineer",
        "data analyst",
        "sre",
        "ux/ui",
        "product design",
    ],
    "languages": [
        "python",
        "javascript",
        "typescript",
        "java",
        "golang",
        "c#",
        "kotlin",
        "swift",
        "rust",
        "sql",
    ],
    "frameworks": [
        "react",
        "node.js",
        "next.js",
        "vue",
        "angular",
        "django",
        "flask",
        "fastapi",
        "spring",
        "react native",
        "flutter",
    ],
    "data_tools": [
        "machine learning",
        "pandas",
        "spark",
        "power bi",
        "tableau",
        "airflow",
    ],
    "design_tools": ["figma", "sketch", "adobe xd"],
    "cloud_devops": [
        "aws",
        "azure",
        "gcp",
        "docker",
        "kubernetes",
        "terraform",
        "ci/cd",
    ],
    "databases": [
        "postgres",
        "mysql",
        "mongodb",
        "redis",
        "elasticsearch",
    ],
    "methodologies": ["agile", "scrum", "kanban", "microservices"],
}

WEAK_IT_SIGNALS = {
    "tech",
    "technology",
    "tecnología",
    "sistemas",
    "informática",
    "computing",
    "it",
    "support",
    "soporte",
    "software",
    "engineer",
    "ingeniero",
    "ingeniera",
    "automation",
    "automatización",
    "testing",
    "pruebas",
    "quality assurance",
    "chef",
    "dev",
    "security",
    "agile",
    "scrum",
    "kanban",
    "mobile",
    "qa",
    "product design",
}

STRONG_TECH_SIGNALS = {
    "python",
    "java",
    "javascript",
    "typescript",
    "react",
    "node.js",
    "nodejs",
    "vue",
    "angular",
    "django",
    "spring",
    ".net",
    "dotnet",
    "aws",
    "azure",
    "gcp",
    "docker",
    "kubernetes",
    "k8s",
    "sql",
    "postgresql",
    "mongodb",
    "figma",
    "sketch",
    "c++",
    "golang",
    "rust",
    "flask",
    "fastapi",
    "laravel",
    "ruby on rails",
}

STRONG_ROLE_SIGNALS = {
    # General - Español
    "desarrollador",
    "desarrolladora",
    "programador",
    "programadora",
    # General - Inglés
    "developer",
    "programmer",
    # Específicos de desarrollo
    "software engineer",
    "ingeniero de software",
    "ingeniera de software",
    "software developer",
    "frontend developer",
    "desarrollador frontend",
    "desarrolladora frontend",
    "backend developer",
    "desarrollador backend",
    "desarrolladora backend",
    "fullstack developer",
    "full stack developer",
    "desarrollador fullstack",
    "desarrolladora fullstack",
    "web developer",
    "desarrollador web",
    "desarrolladora web",
    "mobile developer",
    "desarrollador mobile",
    "desarrolladora mobile",
    # Data
    "data scientist",
    "científico de datos",
    "científica de datos",
    "data engineer",
    "ingeniero de datos",
    "ingeniera de datos",
    "data analyst",
    "analista de datos",
    # DevOps
    "devops engineer",
    "ingeniero devops",
    "ingeniera devops",
    "cloud engineer",
    "ingeniero cloud",
    "ingeniera cloud",
    "sre",
    "site reliability engineer",
    # Design
    "ux designer",
    "ui designer",
    "ux/ui designer",
    "product designer",
    "diseñador ux",
    "diseñadora ux",
    "diseñador ui",
    "diseñadora ui",
    "diseñador ux/ui",
    "diseñadora ux/ui",
    "diseñador de producto",
    "diseñadora de producto",
}

AMBIGUOUS_ROLES = {
    "analyst",
    "analista",
    "coordinator",
    "coordinador",
    "assistant",
    "asistente",
    "specialist",
    "especialista",
    "product owner",
    "product manager",
    "project manager",
    "scrum master",
    "agile coach",
    "owner",
}


REQUIRED_IT_SIGNALS = (
    # Extraer todos los keywords de categorías
    [keyword for category in TAGS_KEYWORDS.values() for keyword in category]
    + [
        # Roles generales - Español
        "desarrollador",
        "programador",
        "programadora",
        "ingeniero",
        "ingeniera",
        "desarrollador web",
        "ingeniero de software",
        "ingeniera de software",
        "analista de sistemas",
        "analista funcional",
        "administrador de sistemas",
        "administradora de sistemas",
        "científico de datos",
        "científica de datos",
        "ingeniero de datos",
        "ingeniera de datos",
        "analista de datos",
        "ingeniero cloud",
        "ingeniera cloud",
        "ingeniero de redes",
        "ingeniera de redes",
        "administrador de redes",
        "administradora de redes",
        "analista de seguridad",
        "ingeniero de seguridad",
        "ingeniera de seguridad",
        "diseñador ux",
        "diseñadora ux",
        "diseñador ui",
        "diseñadora ui",
        "diseñador ux/ui",
        "diseñadora ux/ui",
        "diseñador de producto",
        "diseñadora de producto",
        "diseñador de interacción",
        "diseñadora de interacción",
        "diseñador visual",
        "diseñadora visual",
        # Roles generales - Inglés
        "developer",
        "dev",
        "engineer",
        "programmer",
        "software developer",
        "software engineer",
        "web developer",
        "full stack",
        "full-stack",
        # Data & Analytics
        "systems analyst",
        "bi analyst",
        "bi developer",
        # Sysadmin & DevOps
        "system administrator",
        "infrastructure engineer",
        # QA & Testing
        "qa engineer",
        "quality assurance",
        "qa analyst",
        "qa tester",
        "test automation",
        "automation engineer",
        "automatización",
        # Seguridad
        "cybersecurity",
        "ciberseguridad",
        "pentester",
        "soc analyst",
        "infosec",
        # Soporte
        "soporte técnico",
        "technical support",
        "it support",
        "support engineer",
        "help desk",
        "service desk",
        "mesa de ayuda",
        # UX/UI
        "user experience",
        "experiencia de usuario",
        "user interface",
        "interfaz de usuario",
        "ux research",
        "investigación ux",
        "ui developer",
        "frontend designer",
        "usability",
        "usabilidad",
        "prototyping",
        "prototipado",
        "wireframing",
        "wireframes",
        "user research",
        "investigación de usuarios",
        "design system",
        "sistema de diseño",
        # Redes
        "network analyst",
        "analista de redes",
        # Tecnologías adicionales
        "sqlserver",
        "puppet",
        "chef",
        "travis",
        "cisco",
        "firewall",
        "cortafuegos",
        "vpn",
        "ids",
        "ips",
        "html",
        "css",
        "sass",
        "less",
        "linux",
        "unix",
        "windows server",
        # Conceptos
        "etl",
        "data warehouse",
        "almacén de datos",
        "data pipeline",
        "pipeline de datos",
        "data modeling",
        "modelado de datos",
        "cloud computing",
        "computación en la nube",
        "automation",
        "automatización",
        "testing",
        "pruebas",
        "api gateway",
        "microservices",
        "microservicios",
        "containers",
        "contenedores",
        "software",
        "microservicios",
        "test-driven development",
        "integración continua",
        # Keywords movidos de TAGS_KEYWORDS para mantener el scoring
        "full stack",
        "tester",
        "desarrollador frontend",
        "desarrollador backend",
        "desarrollador fullstack",
        "desarrollador mobile",
        "desarrollador web",
        "desarrollador ios",
        "desarrollador android",
        "científico de datos",
        "ingeniero de datos",
        "ingeniero cloud",
        "ingeniero de redes",
        "administrador de sistemas",
        "soporte técnico",
        "diseñador ux",
        "diseñador ui",
        "diseñador ux/ui",
        "diseñador de producto",
        "data science",
        "sysadmin",
        "security",
        "support",
        "ux",
        "ui",
        "backend engineer",
        "frontend engineer",
        "fullstack developer",
        "mobile developer",
        "ios developer",
        "android developer",
        "web developer",
        "qa engineer",
        "cloud engineer",
        "site reliability engineer",
        "ml engineer",
        "ai engineer",
        "security engineer",
        "platform engineer",
        "business intelligence",
        "analytics engineer",
        "it support",
        "technical support",
        "network engineer",
        "network administrator",
        "cybersecurity analyst",
        "penetration tester",
        "product manager",
        "ux researcher",
        "interaction designer",
        "visual designer",
        "c++",
        "golang",
        "ruby",
        "php",
        "scala",
        "haskell",
        "perl",
        "shell",
        "bash",
        "powershell",
        "dart",
        "elixir",
        "nextjs",
        "nodejs",
        "spring boot",
        ".net",
        "dotnet",
        "express",
        "expressjs",
        "laravel",
        "nestjs",
        "svelte",
        "ember",
        "symfony",
        "ruby on rails",
        "rails",
        "asp.net",
        "blazor",
        "numpy",
        "looker",
        "pyspark",
        "aprendizaje automático",
        "tensorflow",
        "pytorch",
        "scikit-learn",
        "sklearn",
        "hadoop",
        "kafka",
        "hive",
        "superset",
        "mlops",
        "databricks",
        "master data",
        "mdm",
        "invision",
        "zeplin",
        "framer",
        "google cloud",
        "k8s",
        "git",
        "github",
        "gitlab",
        "bitbucket",
        "ansible",
        "jenkins",
        "circleci",
        "gitlab ci",
        "github actions",
        "helm",
        "vault",
        "openshift",
        "cloudformation",
        "pulumi",
        "ftth",
        "postgresql",
        "oracle",
        "mssql",
        "sql server",
        "cassandra",
        "dynamodb",
        "neo4j",
        "mariadb",
        "sqlite",
        "firestore",
        "rest",
        "restful",
        "graphql",
        "api",
        "tdd",
        "bdd",
        "devsecops",
        "continuous integration",
        "continuous deployment",
        # Keywords para roles de Soporte de Producto / TI
        "incidencias",
        "ticket",
        "tickets",
        "ticketing",
        "Zoho",
        "chatbot",
    ]
)

# Eliminar señales débiles de la lista de señales requeridas
REQUIRED_IT_SIGNALS = [s for s in REQUIRED_IT_SIGNALS if s not in WEAK_IT_SIGNALS]

# Eliminar duplicados manteniendo orden
REQUIRED_IT_SIGNALS = list(dict.fromkeys(REQUIRED_IT_SIGNALS))
