EXCLUDED_AREA_TERMS_TITLE = [
    # Finanzas & Contabilidad
    "finanzas",
    "finance",
    "financiero",
    "financial",
    "contador",
    "contadora",
    "accountant",
    "contable",
    "accounting",
    "accounts payable",
    "accounts receivable",
    "cuentas por cobrar",
    "cuentas por pagar",
    "procure to pay",
    "p2p",
    "source to pay",
    "s2p",
    "ap analyst",
    "ar analyst",
    "invoice processing",
    "procesamiento de facturas",
    "impuestos",
    "tax",
    "taxes",
    "taxation",
    "fiscal",
    "tributario",
    "tributaria",
    "tax analyst",
    "analista de impuestos",
    "tax consultant",
    "consultor fiscal",
    "asesor fiscal",
    "asesor tributario",
    "treasury",
    "tesoreria",
    "tesorero",
    "kyc",
    "aml",
    "cobranzas",
    "collector",
    "collections",
    "credit analyst",
    "credito",
    "reaseguros",
    "convenios",
    "procurement",
    "compras",
    "purchasing",
    "buyer",
    "comprador",
    "supplier",
    "underwriter",
    "commodity",
    "commodities",
    "trading",
    "trader",
    "broker",
    "actuario",
    "actuary",
    "fintech strategy specialist",
    "especialista en estrategia fintech"
    # Regulatorio / Legal
    "asuntos regulatorios",
    "regulatory affairs",
    "abogado",
    "abogada",
    "lawyer",
    "attorney",
    "paralegal",
    "legal counsel",
    "compliance officer",
    "legal assistant",
    # RRHH
    "recursos humanos",
    "human resources",
    "rrhh",
    "hr",
    "recruiter",
    "reclutador",
    "reclutadora",
    "talent acquisition",
    "talent management",
    "people operations",
    "people partner",
    # Admin & Asistencia
    "administrativo",
    "administrativa",
    "asistente administrativo",
    "asistente comercial",
    "asistente de ventas",
    "asistente ejecutivo",
    "secretaria",
    "secretario",
    "recepcionista",
    "auxiliar administrativo",
    "office manager",
    # Marketing & Ventas
    "marketing manager",
    "marketing coordinator",
    "mkt",
    "paid media",
    "performance marketing",
    "vendedor",
    "vendedora",
    "sales representative",
    "sales executive",
    "sales manager",
    "gerente de ventas",
    "account manager",
    "gerente de cuentas",
    "salesperson",
    "agente de ventas",
    "sales associate",
    "business development representative",
    "bdr",
    "sdr",
    "inside sales",
    "ventas internas",
    "appointment setter",
    "generador de citas",
    "comercial",
    "ejecutivo comercial",
    "televentas",
    "social media manager",
    "community manager",
    "marketplace specialist",
    "catalog management",
    "brand manager",
    "product marketing",
    "growth hacker",
    # Operaciones & Logística
    "almacén",
    "warehouse",
    "logistics",
    "logistica",
    "supply chain",
    "supply chain analyst",
    "picker",
    "picking",
    "deposito",
    "stockroom",
    "tienda",
    "producción",
    "production",
    "operario",
    "gomero",
    "camiones",
    "truck driver",
    "chofer",
    "driver",
    "procurement specialist",
    "category manager",
    "demand planner",
    "inventory analyst",
    # Servicio al Cliente
    "customer service",
    "atención al cliente",
    "customer success",
    "customer support",
    "call center",
    "contact center",
    # Creativo & Contenido (NO incluir UX/UI aquí)
    "diseñador gráfico",
    "diseñadora gráfica",
    "graphic designer",
    "diseñador industrial",
    "industrial designer",
    "diseñador de modas",
    "fashion designer",
    "diseñador de interiores",
    "interior designer",
    "copywriter",
    "redactor",
    "redactora",
    "content writer",
    "content creator",
    "editor de contenido",
    "audiovisual",
    "video editor",
    "photographer",
    "fotógrafo",
    "traductor",
    "translator",
    "interpreter",
    "intérprete",
    # Educación
    "profesor",
    "profesora",
    "teacher",
    "docente",
    "instructor",
    "tutor",
    "capacitador",
    # Ingeniería NO-Software
    "ingeniero industrial",
    "ingeniero mecánico",
    "ingeniero civil",
    "ingeniero químico",
    "industrial engineer",
    "mechanical engineer",
    "civil engineer",
    "chemical engineer",
    "técnico electrónico",
    "instrumentation",
    "procesos industriales",
    "energías renovables",
    "oil & gas",
    "petroleum",
    "minería",
    "mining",
    # Salud
    "enfermero",
    "enfermera",
    "nurse",
    "médico",
    "médica",
    "doctor",
    "doctora",
    "farmacéutico",
    "farmacéutica",
    "pharmacist",
    "microbiologia",
    "healthcare",
    "hospital",
    "clinic",
    "clínico",
    "biomedical",
    "clinical research",
    "medical assistant",
    # Consultoría No-IT
    "business consultant",
    "management consultant",
    "strategy consultant",
    "consultor de negocios",
    "consultor de gestión",
    "consultor estratégico",
    # Gestión de Proyectos y Programas
    "program manager",
    "programme manager",
    "portfolio manager",
    "gerente de programas",
    "gerente de portafolio",
    "pmo",
    # Otros
    "seguridad fisica",
    "land surveyor",
    "agente inmobiliario",
    "real estate",
    "property manager",
    "cocinero",
    "bartender",
    "camarero",
    "mesero",
    "seguridad e higiene",
    "safety and hygiene",
]
