"""
Este archivo define perfiles de búsqueda de roles específicos.
Cada perfil contiene dos listas:
- 'roles': Títulos de rol que DEBEN estar para que un trabajo sea considerado
           de este perfil.
- 'tech': Palabras clave de tecnologías, herramientas o conceptos. Puede contener
          strings simples o diccionarios para agrupar sinónimos.
"""

PROFILES = {
    "software": {
        "roles": [
            {
                "display": "Frontend Developer",
                "search": [
                    "frontend",
                    "front-end",
                    "front end",
                    "desarrollador frontend",
                    "desarrolladora frontend",
                    "maquetador",
                    "maquetadora",
                    "web designer",
                    "diseñador web",
                    "react developer",
                    "angular developer",
                    "vue developer",
                    "ui developer",
                ],
            },
            {
                "display": "Backend Developer",
                "search": [
                    "backend",
                    "back-end",
                    "back end",
                    "desarrollador backend",
                    "desarrolladora backend",
                    "java developer",
                    "python developer",
                    "node developer",
                    "php developer",
                    "ruby developer",
                    "golang developer",
                    ".net developer",
                    "c# developer",
                    "c++ developer",
                ],
            },
            {
                "display": "Fullstack Developer",
                "search": [
                    "fullstack",
                    "full-stack",
                    "full stack",
                    "desarrollador fullstack",
                    "desarrolladora fullstack",
                ],
            },
            {
                "display": "Mobile Developer",
                "search": [
                    "mobile developer",
                    "desarrollador mobile",
                    "desarrollador movil",
                    "android developer",
                    "ios developer",
                    "flutter developer",
                    "react native developer",
                    "xamarin",
                    "ionic",
                ],
            },
            {
                "display": "Video Game Developer",
                "search": [
                    "game developer",
                    "desarrollador de videojuegos",
                    "unity developer",
                    "unreal developer",
                ],
            },
            {
                "display": "Software Engineer",
                "search": [
                    "software engineer",
                    "ingeniero de software",
                    "ingeniera de software",
                    "software developer",
                    "desarrollador de software",
                    "programador",
                    "programadora",
                    "developer",
                    "programmer",
                ],
            },
        ],
        "tech": [
            # Lenguajes & Core
            {"display": "JavaScript", "search": ["javascript", "js", "es6"]},
            {"display": "TypeScript", "search": ["typescript", "ts"]},
            {"display": "Python", "search": ["python", "py"]},
            {"display": "Java", "search": ["java", "j2ee"]},
            {"display": "C#", "search": ["c#", "csharp", ".net"]},
            {"display": "PHP", "search": ["php"]},
            "ruby",
            "golang",
            "rust",
            # Frontend
            "html",
            "css",
            "sass",
            "less",
            {"display": "React", "search": ["react", "reactjs", "react.js"]},
            {"display": "Angular", "search": ["angular", "angularjs"]},
            {"display": "Vue", "search": ["vue", "vuejs", "vue.js"]},
            {"display": "Next.js", "search": ["next.js", "nextjs"]},
            "svelte",
            "tailwind",
            "bootstrap",
            "jquery",
            # Backend & Frameworks
            {"display": "Node.js", "search": ["node.js", "nodejs", "node"]},
            "express.js",
            "nestjs",
            {"display": "Spring Boot", "search": ["spring", "spring boot"]},
            "django",
            "flask",
            "fastapi",
            "laravel",
            "symfony",
            "asp.net",
            "blazor",
            # Data & APIs
            {"display": "SQL", "search": ["sql", "mysql", "mariadb"]},
            {"display": "PostgreSQL", "search": ["postgresql", "postgres"]},
            {"display": "NoSQL", "search": ["nosql", "mongodb", "mongo"]},
            "redis",
            "firebase",
            "firestore",
            "sqlite",
            {"display": "REST API", "search": ["rest api", "restful", "api rest"]},
            "graphql",
            # Tools
            "git",
            "github",
            "gitlab",
            "docker",
            "kubernetes",
            "linux",
            "bash",
            {"display": "Cloud", "search": ["aws", "azure", "gcp", "google cloud"]},
            {"display": "Testing", "search": ["tdd", "unit testing", "jest", "mocha"]},
        ],
    },
    "data_analytics": {
        "roles": [
            {
                "display": "Data Analyst",
                "search": [
                    "data analyst",
                    "analista de datos",
                    "business analyst",
                    "analista de negocio",
                    "bi analyst",
                    "analista bi",
                ],
            },
            {
                "display": "Data Engineer",
                "search": [
                    "data engineer",
                    "ingeniero de datos",
                    "ingeniera de datos",
                    "etl developer",
                ],
            },
            {
                "display": "Data Scientist",
                "search": [
                    "data scientist",
                    "científico de datos",
                    "científica de datos",
                ],
            },
        ],
        "tech": [
            {"display": "Python", "search": ["python", "pandas", "numpy", "scipy"]},
            {"display": "SQL", "search": ["sql", "t-sql", "pl/sql"]},
            {
                "display": "Excel",
                "search": ["excel", "hojas de calculo", "vba", "macros"],
            },
            {"display": "Power BI", "search": ["power bi", "powerbi", "dax"]},
            "tableau",
            "looker",
            "qlik",
            "r",
            "scala",
            "spark",
            "hadoop",
            "airflow",
            "etl",
            "bigquery",
            "snowflake",
            "redshift",
            "databricks",
        ],
    },
    "design_ux": {
        "roles": [
            {
                "display": "UX/UI Designer",
                "search": [
                    "ux/ui",
                    "ui/ux",
                    "ux designer",
                    "ui designer",
                    "diseñador ux",
                    "diseñador ui",
                    "product designer",
                    "diseñador de producto",
                ],
            },
            {
                "display": "Graphic/Web Designer",
                "search": [
                    "web designer",
                    "diseñador web",
                    "graphic designer",
                    "diseñador grafico",
                ],
            },
        ],
        "tech": [
            "figma",
            "sketch",
            "adobe xd",
            "photoshop",
            "illustrator",
            "indesign",
            "invision",
            "zeplin",
            "miro",
            {
                "display": "Prototyping",
                "search": ["prototyping", "prototipado", "wireframes"],
            },
            {
                "display": "User Research",
                "search": ["user research", "investigación de usuarios"],
            },
            "html",
            "css",
        ],
    },
    "qa": {
        "roles": [
            {
                "display": "QA Automation",
                "search": [
                    "qa automation",
                    "automation engineer",
                    "test automation",
                    "sdet",
                    "automation tester",
                ],
            },
            {
                "display": "QA Manual",
                "search": [
                    "qa manual",
                    "manual tester",
                    "qa tester",
                    "analista qa",
                    "qa analyst",
                    "tester",
                    "qa engineer",
                ],
            },
        ],
        "tech": [
            {"display": "Selenium", "search": ["selenium", "webdriver"]},
            "cypress",
            "playwright",
            "puppeteer",
            "appium",
            {
                "display": "Manual Testing",
                "search": ["pruebas manuales", "test cases", "casos de prueba"],
            },
            "postman",
            "jmeter",
            "soapui",
            "jira",
            "trello",
            "bugzilla",
            "sql",
            "gherkin",
            "cucumber",
        ],
    },
    "devops_sysadmin": {
        "roles": [
            {
                "display": "DevOps Engineer",
                "search": [
                    "devops",
                    "sre",
                    "site reliability engineer",
                    "cloud engineer",
                    "ingeniero cloud",
                    "platform engineer",
                ],
            },
            {
                "display": "SysAdmin / Infra",
                "search": [
                    "sysadmin",
                    "system administrator",
                    "administrador de sistemas",
                    "network administrator",
                    "administrador de redes",
                    "infrastructure engineer",
                    "ingeniero de infraestructura",
                ],
            },
        ],
        "tech": [
            {"display": "AWS", "search": ["aws", "amazon web services"]},
            {"display": "Azure", "search": ["azure"]},
            {"display": "GCP", "search": ["gcp", "google cloud"]},
            {
                "display": "Linux",
                "search": ["linux", "ubuntu", "centos", "red hat", "debian"],
            },
            "docker",
            "kubernetes",
            "terraform",
            "ansible",
            "jenkins",
            "bash",
            "shell scripting",
            "powershell",
            "git",
            "ci/cd",
            "pipelines",
            "nginx",
            "apache",
            {
                "display": "Networking",
                "search": [
                    "tcp/ip",
                    "dns",
                    "dhcp",
                    "vpn",
                    "firewall",
                    "cisco",
                    "routing",
                    "switching",
                ],
            },
            {
                "display": "Virtualization",
                "search": ["vmware", "virtualbox", "hyper-v", "proxmox"],
            },
        ],
    },
    "cybersecurity": {
        "roles": [
            {
                "display": "Cybersecurity Analyst",
                "search": [
                    "cybersecurity",
                    "ciberseguridad",
                    "seguridad informatica",
                    "security analyst",
                    "analista de seguridad",
                    "soc analyst",
                    "blue team",
                ],
            },
            {
                "display": "Pentester",
                "search": [
                    "pentester",
                    "penetration tester",
                    "ethical hacker",
                    "red team",
                    "vulnerability analyst",
                ],
            },
        ],
        "tech": [
            "siem",
            "soc",
            "firewall",
            "ids",
            "ips",
            "wireshark",
            "nmap",
            "metasploit",
            "burp suite",
            "nessus",
            "owasp",
            "iso 27001",
            "pci dss",
            "linux",
            "kali linux",
            "python",
            "bash",
            {"display": "Identity", "search": ["iam", "active directory", "azure ad"]},
        ],
    },
    "machine_learning_ai": {
        "roles": [
            {
                "display": "AI/ML Engineer",
                "search": [
                    "machine learning",
                    "aprendizaje automatico",
                    "ai engineer",
                    "ingeniero de ia",
                    "ml engineer",
                    "deep learning",
                ],
            }
        ],
        "tech": [
            "python",
            "tensorflow",
            "pytorch",
            "keras",
            "scikit-learn",
            "pandas",
            "numpy",
            "opencv",
            {
                "display": "NLP",
                "search": ["nlp", "natural language processing", "nltk", "spacy"],
            },
            {
                "display": "LLM",
                "search": ["llm", "langchain", "hugging face", "openai api"],
            },
        ],
    },
    "tech_support": {
        "roles": [
            {
                "display": "IT Support / Help Desk",
                "search": [
                    "help desk",
                    "mesa de ayuda",
                    "soporte tecnico",
                    "technical support",
                    "it support",
                    "soporte it",
                    "tecnico informatico",
                    "service desk",
                    "desktop support",
                ],
            }
        ],
        "tech": [
            {"display": "Windows", "search": ["windows", "windows 10", "windows 11"]},
            {
                "display": "Hardware",
                "search": [
                    "hardware",
                    "armado y reparacion",
                    "mantenimiento",
                    "perifericos",
                    "impresoras",
                ],
            },
            {
                "display": "Office 365",
                "search": ["office 365", "o365", "outlook", "excel", "word"],
            },
            {
                "display": "Active Directory",
                "search": ["active directory", "ad", "azure ad", "usuarios"],
            },
            {
                "display": "Ticketing",
                "search": ["jira", "servicenow", "zendesk", "tickets", "glpi"],
            },
            {
                "display": "Remote Tools",
                "search": ["teamviewer", "anydesk", "remote desktop", "rdp"],
            },
            "redes",
            "lan",
            "wifi",
            "cableado",
        ],
    },
}
