"""
Este archivo define perfiles de búsqueda de roles específicos.
Cada perfil contiene dos listas:
- 'roles': Títulos de rol que DEBEN estar para que un trabajo sea considerado
           de este perfil.
- 'tech': Palabras clave de tecnologías, herramientas o conceptos. Puede contener
          strings simples o diccionarios para agrupar sinónimos.
"""

PROFILES = {
    "software": {
        "roles": [
            "desarrollador",
            "desarrolladora",
            "programador",
            "programadora",
            "developer",
            "programmer",
            "software engineer",
            "ingeniero de software",
            "ingeniera de software",
            "software developer",
            "frontend developer",
            "desarrollador frontend",
            "desarrolladora frontend",
            "frontend engineer",
            "web developer",
            "desarrollador web",
            "desarrolladora web",
            "backend developer",
            "desarrollador backend",
            "desarrolladora backend",
            "backend engineer",
            "fullstack developer",
            "desarrollador fullstack",
            "desarrolladora fullstack",
            "full stack",
            "full-stack",
            "fullstack",
            "game developer",
            "desarrollador de videojuegos",
            "embedded engineer",
            "iot developer",
            "firmware engineer",
        ],
        "tech": [
            "python",
            "java",
            "javascript",
            "typescript",
            "c++",
            "c#",
            "golang",
            "rust",
            "ruby",
            "php",
            "elixir",
            "clojure",
            "lua",
            "vue",
            "angular",
            "svelte",
            "ember",
            "html",
            "css",
            "sass",
            "less",
            "django",
            "flask",
            "fastapi",
            "expressjs",
            "nestjs",
            "symfony",
            "laravel",
            "ruby on rails",
            "asp.net",
            "blazor",
            "sql",
            "postgresql",
            "mysql",
            "mongodb",
            "redis",
            "elasticsearch",
            "oracle",
            "mssql",
            "cassandra",
            "dynamodb",
            "neo4j",
            "mariadb",
            "sqlite",
            "firestore",
            "postgres",
            "api",
            "graphql",
            "unity",
            "unreal engine",
            "api gateway",
            "git",
            "github",
            "gitlab",
            "bitbucket",
            "docker",
            "kubernetes",
            "tdd",
            "bdd",
            {"display": "react", "search": ["react", "reactjs", "react.js"]},
            {"display": "node.js", "search": ["node.js", "nodejs"]},
            {"display": "next.js", "search": ["next.js", "nextjs"]},
            {"display": "spring", "search": ["spring", "spring boot"]},
            {"display": "rest api", "search": ["rest", "restful", "rest api"]},
            {"display": "microservices", "search": ["microservices", "microservicios"]},
            {
                "display": "cloud computing",
                "search": ["cloud computing", "computación en la nube"],
            },
        ],
    },
    "design_ux": {
        "roles": [
            "ux designer",
            "ui designer",
            "ux/ui designer",
            "product designer",
            "diseñador ux",
            "diseñadora ux",
            "diseñador ui",
            "diseñadora ui",
            "diseñador ux/ui",
            "diseñadora ux/ui",
            "diseñador de producto",
            "diseñadora de producto",
            "ux researcher",
            "interaction designer",
            "visual designer",
            "diseñador de interacción",
            "diseñadora de interacción",
            "diseñador visual",
            "diseñadora visual",
            "ui developer",
            "frontend designer",
        ],
        "tech": [
            "ux",
            "ui",
            "figma",
            "sketch",
            "adobe xd",
            "invision",
            "zeplin",
            "framer",
            "user research",
            {"display": "ux/ui", "search": ["ux/ui", "ui/ux"]},
            {
                "display": "design system",
                "search": ["design system", "sistema de diseño"],
            },
            {
                "display": "diseño de producto",
                "search": ["diseño de producto", "product design"],
            },
        ],
    },
    "mobile_dev": {
        "roles": [
            "mobile developer",
            "desarrollador mobile",
            "desarrolladora mobile",
            "ios developer",
            "desarrollador ios",
            "android developer",
            "desarrollador android",
        ],
        "tech": [
            "mobile",
            "ios",
            "android",
            "swift",
            "kotlin",
            "flutter",
            "dart",
            "git",
            "github",
            "gitlab",
            "bitbucket",
            "tdd",
            "bdd",
            {"display": "react native", "search": ["react native", "react-native"]},
        ],
    },
    "data_analytics": {
        "roles": [
            "data analyst",
            "analista de datos",
            "bi analyst",
            "bi developer",
            "data engineer",
            "ingeniero de datos",
            "ingeniera de datos",
            "data scientist",
            "científico de datos",
            "científica de datos",
            "analytics engineer",
            "big data engineer",
        ],
        "tech": [
            "python",
            "sql",
            "matlab",
            "scala",
            "pandas",
            "spark",
            "pyspark",
            "numpy",
            "hadoop",
            "hive",
            "airflow",
            "kafka",
            "etl",
            "data warehouse",
            "data pipeline",
            "data modeling",
            "looker",
            "tableau",
            "power bi",
            "superset",
            "databricks",
            "microstrategy",
            "spss modeler",
            "excel",
            "jupyter",
            {"display": "data science", "search": ["data science", "ciencia de datos"]},
            {
                "display": "business intelligence",
                "search": ["business intelligence", "bi"],
            },
            {"display": "r", "search": ["r language", "r programming"]},
        ],
    },
    "devops_sysadmin": {
        "roles": [
            "devops engineer",
            "ingeniero devops",
            "ingeniera devops",
            "sre",
            "site reliability engineer",
            "cloud engineer",
            "ingeniero cloud",
            "ingeniera cloud",
            "platform engineer",
            "infrastructure engineer",
            "administrador de sistemas",
            "administradora de sistemas",
            "system administrator",
            "sysadmin",
            "network administrator",
            "administrador de redes",
            "administradora de redes",
            "network engineer",
            "ingeniero de redes",
            "ingeniera de redes",
        ],
        "tech": [
            "devops",
            "cloud",
            "aws",
            "azure",
            "docker",
            "terraform",
            "ansible",
            "jenkins",
            "ci/cd",
            "helm",
            "vault",
            "openshift",
            "cloudformation",
            "pulumi",
            "devsecops",
            "puppet",
            "travis",
            "linux",
            "unix",
            "bash",
            "powershell",
            "windows server",
            "hyper-v",
            "vmware",
            "cisco",
            "proxy",
            "tcp",
            "enrutamiento",
            "routing",
            "conmutacion",
            "switching",
            "monitoring",
            "grafana",
            "prometheus",
            "git",
            "github",
            "gitlab",
            "bitbucket",
            {"display": "gcp", "search": ["gcp", "google cloud"]},
            {"display": "kubernetes", "search": ["kubernetes", "k8s"]},
            {"display": "containers", "search": ["containers", "contenedores"]},
            {
                "display": "cloud computing",
                "search": ["cloud computing", "computación en la nube"],
            },
            {
                "display": "server virtualization",
                "search": ["virtualización de servidores", "server virtualization"],
            },
            {"display": "lan", "search": ["redes lan", "lan networks"]},
            {"display": "wan", "search": ["redes wan", "wan networks"]},
            {
                "display": "network monitoring",
                "search": ["network monitoring", "monitorización de redes"],
            },
            {
                "display": "disaster recovery",
                "search": ["disaster recovery", "backup and recovery"],
            },
            {
                "display": "network protocols",
                "search": ["protocolos de red", "network protocols"],
            },
            {
                "display": "access networks",
                "search": ["redes de acceso", "access networks"],
            },
            {"display": "ip technology", "search": ["tecnologia ip", "ip technology"]},
            {
                "display": "network optimization",
                "search": ["optimizacion de redes", "network optimization"],
            },
            {
                "display": "operating systems",
                "search": ["sistemas operativos", "operating systems"],
            },
            {
                "display": "windows administration",
                "search": ["windows administration", "administración de windows"],
            },
            {"display": "databases", "search": ["databases", "bases de datos"]},
            {
                "display": "sharepoint administration",
                "search": ["sharepoint administration", "administración de sharepoint"],
            },
        ],
    },
    "qa": {
        "roles": [
            "qa engineer",
            "quality assurance",
            "qa analyst",
            "qa tester",
            "test automation",
            "automation engineer",
            "tester",
            "qa gaming analyst",
            "analista qa",
        ],
        "tech": [
            "automation",
            "automatización",
            "qa",
            "selenium",
            "cypress",
            "tdd",
            "bdd",
            {"display": "testing", "search": ["testing", "pruebas"]},
            {
                "display": "regression testing",
                "search": ["pruebas de regresión", "regression testing"],
            },
            {
                "display": "functional testing",
                "search": ["pruebas funcionales", "functional testing"],
            },
            {
                "display": "performance testing",
                "search": ["pruebas de rendimiento", "performance testing"],
            },
        ],
    },
    "cybersecurity": {
        "roles": [
            "cybersecurity analyst",
            "penetration tester",
            "security engineer",
            "pentester",
            "soc analyst",
            "analista de seguridad",
            "ingeniero de seguridad",
            "ingeniera de seguridad",
        ],
        "tech": [
            "cybersecurity",
            "ciberseguridad",
            "firewall",
            "firewalls",
            "cortafuegos",
            "soc",
            "siem",
            "soar",
            "vpn",
            "ids",
            "ips",
            "active directory",
            "azure ad",
            "entra id",
            "devsecops",
            {
                "display": "information security",
                "search": ["information security", "seguridad informática", "infosec"],
            },
            {
                "display": "firewall configuration",
                "search": ["firewall configuration", "configuración de firewall"],
            },
        ],
    },
    "machine_learning_ai": {
        "roles": [
            "ml engineer",
            "ai engineer",
            "machine learning engineer",
            "artificial intelligence engineer",
            "machine learning scientist",
            "ai scientist",
        ],
        "tech": [
            "mlops",
            "deep learning",
            "nlp",
            "natural language processing",
            "computer vision",
            "tensorflow",
            "pytorch",
            "scikit-learn",
            "sklearn",
            {
                "display": "machine learning",
                "search": ["machine learning", "aprendizaje automático"],
            },
            {
                "display": "artificial intelligence",
                "search": ["artificial intelligence", "ia", "inteligencia artificial"],
            },
        ],
    },
    "tech_support": {
        "roles": [
            "soporte técnico",
            "soporte tecnico",
            "soporte it",
            "technical support",
            "desktop support",
            "help desk",
            "service desk",
            "it support specialist",
            "computer technician",
            "tecnico informatico",
            "support engineer",
            "Data Support Analyst",
            "Analista de Soporte de Datos",
        ],
        "tech": [
            "hardware",
            "windows",
            "microsoft office",
            "redes",
            "ftth",
            "chatbot",
            "mesa de ayuda",
            "incidencias",
            "ticket",
            "tickets",
            "ticketing",
            "zoho",
            {
                "display": "ticketing system",
                "search": ["ticketing system", "sistema de tickets"],
            },
            {
                "display": "incident resolution",
                "search": ["resolución de incidentes", "incident resolution"],
            },
            {
                "display": "computer hardware maintenance",
                "search": [
                    "mantenimiento de equipos informáticos",
                    "computer hardware maintenance",
                ],
            },
            {
                "display": "hardware installation",
                "search": ["instalación de hardware", "hardware installation"],
            },
            {
                "display": "onedrive administration",
                "search": ["administración de onedrive", "onedrive administration"],
            },
        ],
    },
}
