POSITIVE_SENIORITY_TERMS = {
    # --- Inglés ---
    "trainee",
    "junior",
    "jr",
    "jr.",
    "entry level",
    "entry-level",
    "internship",
    "intern",
    "graduate",
    "student",
    "grad",
    "beginner",
    "fresher",
    "associate",
    "apprentice",
    "apprenticeship",
    "no experience",
    "level 1",
    "level i",
    "l1",
    # --- Español ---
    "pasantia",
    "pasantía",
    "pasante",
    "graduado",
    "recien graduado",
    "recién graduado",
    "becario",
    "aprendiz",
    "inicial",
    "estudiante",
    "practicas",
    "prácticas",
    "practicante",
    "sin experiencia",
    "primer empleo",
    "joven profesional",
    "jovenes profesionales",
    "semillero",
    "escuela",
    "bootcamp",
    "academy",
    "nivel 1",
    "nivel inicial",
}

EXCLUDED_SENIORITY_TERMS = {
    # --- Seniority Explícito ---
    "senior",
    "sr.",
    "sr",
    "srr",
    "semi senior",
    "semi-senior",
    "semisenior",
    "ssr.",
    "ssr",
    "mid",
    "mid-level",
    "mid level",
    "intermediate",
    "intermedio",
    "advanced",
    "avanzado",
    "experienced",
    "experimentado",
    # --- Roles de Liderazgo/Gestión ---
    "tech lead",
    "team lead",
    "squad lead",
    "lead",
    "lider",
    "líder",
    "manager",
    "management",
    "director",
    "head",
    "head of",
    "jefe",
    "jefa",
    "chief",
    "gerente",
    "coordinador",
    "supervisor",
    "principal",
    "staff",
    # --- Expertos/Arquitectura ---
    "architect",
    "arquitecto",
    "arquitecta",
    "expert",
    "experto",
    "specialist",
    "especialista",
    "consultant",
    "consultor",
    # --- Niveles Altos ---
    "iii",
    "iv",
    "v",
    "level 2",
    "level 3",
    "level 4",
    "nivel 2",
    "nivel 3",
}
