POSITIVE_SENIORITY_TERMS = {
    # Inglés
    "trainee",
    "junior",
    "jr",
    "jr.",
    "entry level",
    "entry-level",
    "internship",
    "intern",
    "graduate",
    "student",
    "grad",
    "beginner",
    "no experience",
    "level 1",
    "level 2",
    "i",
    "ii",
    # Español
    "pasantia",
    "pasante",
    "graduado",
    "recien graduado",
    "becario",
    "aprendiz",
    "inicial",
    "estudiante",
    "practicas",
    "practicante",
    "sin experiencia",
    "primer empleo",
    "nivel 1",
    "nivel 2",
}


EXCLUDED_SENIORITY_TERMS = [
    # Senior explícito
    "senior",
    "sr.",
    "sr",
    "semi senior",
    "semi-senior",
    "semisenior",
    "ssr.",
    "ssr",
    # Roles compuestos que son claramente senior
    "tech lead",
    "team lead",
    "squad lead",
    "lead developer",
    "lead engineer",
    "lider tecnico",
    "lider de equipo",
    "líder técnico",
    "líder de equipo",
    "staff engineer",
    "staff developer",
    # Management
    "manager",
    "director",
    "head of",
    "jefe de",
    "jefa de",
    "chief",
    "gerente",
    "coordinador de",
    "supervisor",
    # Expertos
    "principal engineer",
    "principal developer",
    "architect",
    "arquitecto de",
    "expert",
    "experto",
    "especialista senior",
    # Niveles altos
    "iii",
    "iv",
    "v",
    "level 3",
    "level 4",
    "nivel 3",
    "nivel 4",
]
