POSITIVE_SENIORITY_TERMS = {
    # Inglés
    "trainee",
    "junior",
    "jr",
    "jr.",
    "entry level",
    "entry-level",
    "internship",
    "intern",
    "graduate",
    "student",
    "grad",
    "no experience",
    "first job",
    "beginner",
    # Español
    "pasantía",
    "pasante",
    "sin experiencia",
    "primer empleo",
    "primer trabajo",
    "graduado",
    "recién graduado",
    "becario",
    "aprendiz",
    "inicial",
    "estudiante",
}

EXCLUDED_SENIORITYS = [
    # Niveles Senior
    "senior",
    "sr",
    "sr.",
    "ssr",
    "semi senior",
    "semi-senior",
    "semisenior",
    # Niveles de Liderazgo
    "lead",
    "líder",
    "lider",
    "manager",
    "director",
    "head",
    "jefe",
    "jefa",
    "chief",
    "gerente",
    "coordinador",
    "coordinator",
    "supervisor",
    # Niveles Avanzados
    "principal",
    "staff",
    "expert",
    "experto",
    # Indicadores de Nivel/Años
    " ii",
    " iii",
    " iv",
    " v",
    "level 2",
    "level 3",
    "level 4",
    "nivel 2",
    "nivel 3",
    "nivel 4",
    "pl",
    "pleno",
    "3+",
    "4+",
    "5+",
    "+3",
    "+4",
    "+5",
]
