WEAK_IT_SIGNALS = {
    "tech",
    "technology",
    "tecnología",
    "sistemas",
    "informática",
    "computing",
    "software",
    "automation",
    "automatización",
    "testing",
    "pruebas",
    "agile",
    "scrum",
    "kanban",
}

STRONG_TECH_SIGNALS = {
    # Languages
    "python",
    "java",
    "javascript",
    "typescript",
    "c++",
    "c#",
    "golang",
    "rust",
    "ruby",
    "php",
    "swift",
    "kotlin",
    "scala",
    "dart",
    "powershell",
    "bash",
    "perl",
    "shell",
    "elixir",
    "clojure",
    "lua",
    "matlab",
    "r language",
    "r programming",
    # Frameworks & Libraries
    "react",
    "react native",
    "node.js",
    "nodejs",
    "next.js",
    "nextjs",
    "vue",
    "angular",
    "svelte",
    "django",
    "flask",
    "fastapi",
    "spring",
    "spring boot",
    "expressjs",
    "express.js",
    "nestjs",
    "ember",
    "symfony",
    "laravel",
    "ruby on rails",
    "flutter",
    "selenium",
    "cypress",
    "pandas",
    "spark",
    "unreal engine",
    "unity",
    "asp.net",
    "blazor",
    ".net",
    "dotnet",
    "pyspark",
    # Cloud & DevOps
    "aws",
    "azure",
    "gcp",
    "google cloud",
    "docker",
    "kubernetes",
    "k8s",
    "terraform",
    "ansible",
    "jenkins",
    "ci/cd",
    "git",
    "github",
    "gitlab",
    "bitbucket",
    "circleci",
    "helm",
    "vault",
    "openshift",
    "cloudformation",
    "pulumi",
    "devsecops",
    # Databases
    "sql",
    "sql server",
    "postgresql",
    "mysql",
    "mongodb",
    "redis",
    "elasticsearch",
    "oracle",
    "mssql",
    "cassandra",
    "dynamodb",
    "neo4j",
    "mariadb",
    "sqlite",
    "firestore",
    # Architecture & Concepts
    "full stack",
    "full-stack",
    "etl",
    "data warehouse",
    "data pipeline",
    "data modeling",
    "api gateway",
    "microservices",
    "microservicios",
    "containers",
    "contenedores",
    "rest",
    "restful",
    "graphql",
    "api",
    "tdd",
    "bdd",
    "cloud computing",
    "computación en la nube",
    # Data Science & ML
    "data science",
    "business intelligence",
    "machine learning",
    "mlops",
    "numpy",
    "looker",
    "aprendizaje automático",
    "tensorflow",
    "pytorch",
    "scikit-learn",
    "sklearn",
    "hadoop",
    "hive",
    "superset",
    "databricks",
    # Design
    "figma",
    "sketch",
    "invision",
    "zeplin",
    "framer",
    "design system",
    "sistema de diseño",
    # BPM & Other Tools
    "bpm",
    "bpmn",
    "bizagi",
    "aris",
    "tableau",
    "power bi",
    "kafka",
    "airflow",
    # Security
    "cybersecurity",
    "ciberseguridad",
    "infosec",
    "seguridad informática",
    "seguridad informatica",
    "information security",
    "firewall",
    "cortafuegos",
    "vpn",
    "ids",
    "ips",
    "active directory",
    "controlador de dominio",
    "domain controller",
    "azure ad",
    "entra id",
    # Front-end/Web & Infra-Específico
    "html",
    "css",
    "sass",
    "less",
    "linux",
    "unix",
    "windows server",
    "virtualización de servidores",
    "server virtualization",
    "hyper-v",
    "vmware",
    "redes lan",
    "redes wan",
    "network monitoring",
    "monitorización de redes",
    "backup and recovery",
    "disaster recovery",
}

STRONG_ROLE_SIGNALS = {
    # Roles General - Español
    "desarrollador",
    "desarrolladora",
    "programador",
    "programadora",
    # Roles General - Inglés
    "developer",
    "programmer",
    # Específicos de desarrollo
    "software engineer",
    "ingeniero de software",
    "ingeniera de software",
    "software developer",
    "frontend developer",
    "desarrollador frontend",
    "desarrolladora frontend",
    "backend developer",
    "desarrollador backend",
    "desarrolladora backend",
    "fullstack developer",
    "desarrollador fullstack",
    "desarrolladora fullstack",
    "web developer",
    "desarrollador web",
    "desarrolladora web",
    "mobile developer",
    "desarrollador mobile",
    "desarrolladora mobile",
    "desarrollador ios",
    "desarrollador android",
    "ios developer",
    "android developer",
    "backend engineer",
    "frontend engineer",
    "platform engineer",
    # Data
    "data scientist",
    "científico de datos",
    "científica de datos",
    "data engineer",
    "ingeniero de datos",
    "ingeniera de datos",
    "data analyst",
    "analista de datos",
    "systems analyst",
    "analista de sistemas",
    "analista funcional",
    "bi analyst",
    "bi developer",
    "ml engineer",
    "ai engineer",
    "analytics engineer",
    "big data engineer",
    # DevOps
    "devops engineer",
    "ingeniero devops",
    "ingeniera devops",
    "cloud engineer",
    "ingeniero cloud",
    "ingeniera cloud",
    "sre",
    "site reliability engineer",
    "infrastructure engineer",
    # QA
    "qa engineer",
    "quality assurance",
    "qa analyst",
    "qa tester",
    "test automation",
    "automation engineer",
    "tester",
    # Security
    "cybersecurity analyst",
    "penetration tester",
    "security engineer",
    "pentester",
    "soc analyst",
    "analista de seguridad",
    "ingeniero de seguridad",
    "ingeniera de seguridad",
    # Game Development
    "game developer",
    "desarrollador de videojuegos",
    # Design
    "ux designer",
    "ui designer",
    "ux/ui designer",
    "product designer",
    "diseñador ux",
    "diseñadora ux",
    "diseñador ui",
    "diseñadora ui",
    "diseñador ux/ui",
    "diseñadora ux/ui",
    "diseñador de producto",
    "diseñadora de producto",
    "ux researcher",
    "interaction designer",
    "visual designer",
    "diseñador de interacción",
    "diseñadora de interacción",
    "diseñador visual",
    "diseñadora visual",
    "ui developer",
    "frontend designer",
    # Support & Infrastructure
    "Data Support Analyst",
    "Analista de Soporte de Datos",
    "soporte técnico",
    "soporte técnico informático",
    "soporte tecnico informatico",
    "soporte técnico it",
    "soporte tecnico it",
    "soporte it",
    "support engineer",
    "it support specialist",
    "technical support specialist",
    "help desk technician",
    "service desk analyst",
    "desktop support",
    "administrador de sistemas",
    "administradora de sistemas",
    "system administrator",
    "sysadmin",
    "network analyst",
    "analista de redes",
    "network engineer",
    "network administrator",
    "administrador de redes",
    "administradora de redes",
    "ingeniero de redes",
    "ingeniera de redes",
    "tech lead",
    "team lead",
    "líder técnico",
    "lider tecnico",
    "líder de equipo",
    "lider de equipo",
    "scrum master",
    "agile coach",
    "solution architect",
    "cloud architect",
    "data architect",
    "arquitecto de soluciones",
    "arquitecto cloud",
    "arquitecto de datos",
    "arquitecta de soluciones",
    "arquitecta cloud",
    "arquitecta de datos",
}

AMBIGUOUS_ROLES = {
    "analyst",
    "analista",
    "business analyst",
    "ba",
    "coordinator",
    "coordinador",
    "assistant",
    "asistente",
    "specialist",
    "especialista",
    "owner",
    "consultant",
    "consultor",
    "consultora",
    "project manager",
    "consultor de procesos",
    "process consultant",
    "engineer",
    "ingeniero",
    "ingeniera",
    "architect",
    "arquitecto",
    "arquitecta",
    "product owner",
    "product manager",
}

REQUIRED_IT_SIGNALS = [
    # Gestión IT y Hardware
    "gestión de inventario it",
    "gestión de inventario ti",
    "it inventory management",
    "gestión de activos it",
    "it asset management",
    "sistema de tickets",
    "ticketing system",
    "gestión de incidencias it",
    "it incident management",
    "resolución de incidentes",
    "incident resolution",
    "ftth",
    "mantenimiento de equipos informáticos",
    "mantenimiento de equipos informaticos",
    "computer hardware maintenance",
    "instalación de hardware",
    "hardware installation",
    "administración de onedrive",
    "administracion de onedrive",
    "sharepoint administration",
    "administración de sharepoint",
    "firewall configuration",
    "configuración de firewall",
    "puppet",
    "travis",
    # Contexto Académico
    "licenciatura en sistemas",
    "lic en sistemas",
    "lic. en sistemas",
    "systems engineering",
    "ingeniería de sistemas",
    "computer science",
    "ciencias de la computación",
    "ciencia de datos",
    "information technology",
    "tecnologías de la información",
    # Conceptos y Herramientas no cubiertas en STRONG_TECH o WEAK_IT
    "cisco",
    "redes LAN",
    "lan networks",
    "redes WAN",
    "wan networks",
    "sistemas operativos",
    "operating systems",
    "sistema operativo windows",
    "sistema operativo linux",
    "windows administration",
    "administración de windows",
    "data warehouse",
    "almacén de datos",
    "data pipeline",
    "pipeline de datos",
    "data modeling",
    "modelado de datos",
    # Términos de Soporte específicos
    "incidencias",
    "ticket",
    "tickets",
    "ticketing",
    "zoho",
    "chatbot",
    "mesa de ayuda",
]


#    Eliminar términos que ya están en las listas más fuertes o más débiles
REQUIRED_IT_SIGNALS = [
    s
    for s in REQUIRED_IT_SIGNALS
    if s not in WEAK_IT_SIGNALS
    and s not in STRONG_TECH_SIGNALS
    and s not in STRONG_ROLE_SIGNALS
]

# 5. ELIMINAR DUPLICADOS MANTENIENDO ORDEN
REQUIRED_IT_SIGNALS = list(dict.fromkeys(REQUIRED_IT_SIGNALS))
