# Señales que confirman que un rol ambiguo es de IT
IT_CONTEXT_SIGNALS = {
    # Generales
    "it",
    "ti",
    "tech",
    "technology",
    "tecnología",
    "tecnologia",
    "sistemas",
    "informática",
    "informatica",
    "computación",
    "computacion",
    "digital",
    "software",
    "hardware",
    "web",
    "app",
    "mobile",
    "cloud",
    "programación",
    "programacion",
    "development",
    "desarrollo",
    "coding",
    "codigo",
    "código",
    "agile",
    "scrum",
    # Educación (Filtro fuerte)
    "licenciatura en sistemas",
    "lic en sistemas",
    "ingeniería de sistemas",
    "ingenieria de sistemas",
    "computer science",
    "ciencias de la computación",
    "ciencia de datos",
    "data science",
    "ingeniería informática",
    "ingenieria informatica",
    "tecnicatura en programación",
    "analista de sistemas",
}

# Roles que existen en OTROS rubros y requieren verificación de contexto
AMBIGUOUS_ROLES = {
    "analyst",
    "analista",
    "business analyst",
    "ba",
    "analista funcional",
    "consultant",
    "consultor",
    "consultora",
    "coordinator",
    "coordinador",
    "coordinadora",
    "assistant",
    "asistente",
    "manager",
    "gerente",
    "project manager",
    "pm",
    "product owner",
    "po",
    "product manager",
    "engineer",
    "ingeniero",
    "ingeniera",
    "architect",
    "arquitecto",
    "arquitecta",
    "specialist",
    "especialista",
    "designer",
    "diseñador",
    "diseñadora",
    "graphic designer",
    "diseñador grafico",
    "support",
    "soporte",
    "atención al cliente",
    "help desk",
    "tester",
    "operator",
    "operador",
    "administrator",
    "administrador",
}

# Señales débiles que por sí solas NO confirman un rol IT (requieren contexto fuerte)
WEAK_IT_SIGNALS = {
    # Office / Admin
    "excel",
    "word",
    "powerpoint",
    "outlook",
    "office 365",
    "o365",
    "microsoft office",
    # BI / Data (Contexto débil si no hay rol IT)
    "power bi",
    "tableau",
    "looker",
    "qlik",
    "vba",
    "macros",
    # OS Genéricos
    "windows",
    "windows 10",
    "windows 11",
    # Diseño (Contexto dependiente)
    "photoshop",
    "illustrator",
    "indesign",
    "corel draw",
    # CMS (Contexto dependiente)
    "wordpress",
    "joomla",
    "drupal",
}
