from filters_scoring_config.tags import TAGS_KEYWORDS


WEAK_IT_SIGNALS = {
    "tech",
    "technology",
    "tecnología",
    "sistemas",
    "informática",
    "computing",
    "software",
    "engineer",
    "ingeniero",
    "ingeniera",
    "automation",
    "automatización",
    "testing",
    "pruebas",
    "quality assurance",
    "agile",
    "scrum",
    "kanban",
}

STRONG_TECH_SIGNALS = {
    "python",
    "java",
    "javascript",
    "typescript",
    "react",
    "node.js",
    "nodejs",
    "vue",
    "angular",
    "django",
    "spring",
    ".net",
    "dotnet",
    "aws",
    "azure",
    "gcp",
    "docker",
    "kubernetes",
    "k8s",
    "sql",
    "postgresql",
    "mysql",
    "mongodb",
    "redis",
    "elasticsearch",
    "figma",
    "sketch",
    "c++",
    "golang",
    "rust",
    "flask",
    "fastapi",
    "laravel",
    "ruby on rails",
    "terraform",
    "jenkins",
    "ansible",
    "pandas",
    "spark",
    "tableau",
    "power bi",
    "kafka",
}

STRONG_ROLE_SIGNALS = {
    # General - Español
    "desarrollador",
    "desarrolladora",
    "programador",
    "programadora",
    # General - Inglés
    "developer",
    "programmer",
    # Específicos de desarrollo
    "software engineer",
    "ingeniero de software",
    "ingeniera de software",
    "software developer",
    "frontend developer",
    "desarrollador frontend",
    "desarrolladora frontend",
    "backend developer",
    "desarrollador backend",
    "desarrolladora backend",
    "fullstack developer",
    "full stack developer",
    "desarrollador fullstack",
    "desarrolladora fullstack",
    "web developer",
    "desarrollador web",
    "desarrolladora web",
    "mobile developer",
    "desarrollador mobile",
    "desarrolladora mobile",
    # Data
    "data scientist",
    "científico de datos",
    "científica de datos",
    "data engineer",
    "ingeniero de datos",
    "ingeniera de datos",
    "data analyst",
    "analista de datos",
    # DevOps
    "devops engineer",
    "ingeniero devops",
    "ingeniera devops",
    "cloud engineer",
    "ingeniero cloud",
    "ingeniera cloud",
    "sre",
    "site reliability engineer",
    # Design
    "ux designer",
    "ui designer",
    "ux/ui designer",
    "product designer",
    "diseñador ux",
    "diseñadora ux",
    "diseñador ui",
    "diseñadora ui",
    "diseñador ux/ui",
    "diseñadora ux/ui",
    "diseñador de producto",
    "diseñadora de producto",
    # Support & Infrastructure
    "Data Support Analyst",
    "Analista de Soporte de Datos",
    "soporte técnico informático",
    "soporte tecnico informatico",
    "técnico de soporte it",
    "tecnico de soporte it",
    "especialista en soporte it",
    "técnico informático",
    "tecnico informatico",
    "administrador de sistemas",
    "técnico de redes",
    "tecnico de redes",
    "it support specialist",
    "technical support specialist",
    "help desk technician",
    "service desk analyst",
    "systems administrator",
    "network technician",
    "desktop support",
}

AMBIGUOUS_ROLES = {
    "analyst",
    "analista",
    "business analyst",
    "ba",
    "coordinator",
    "coordinador",
    "assistant",
    "asistente",
    "specialist",
    "especialista",
    "product owner",
    "product manager",
    "project manager",
    "scrum master",
    "agile coach",
    "owner",
    "consultant",
    "consultor",
    "consultora",
    "engineer",
    "ingeniero",
    "ingeniera",
}

REQUIRED_IT_SIGNALS = (
    # Extraer todos los keywords de categorías
    [
        term
        for category in TAGS_KEYWORDS.values()
        for tag_info in category
        for term in tag_info["search_terms"]
    ]
    + [
        # Roles generales - Español
        "desarrollador",
        "desarrolladora",
        "programador",
        "programadora",
        "ingeniero",
        "ingeniera",
        "desarrollador web",
        "ingeniero de software",
        "ingeniera de software",
        "analista de sistemas",
        "analista funcional",
        "administrador de sistemas",
        "administradora de sistemas",
        "científico de datos",
        "científica de datos",
        "ingeniero de datos",
        "ingeniera de datos",
        "analista de datos",
        "ingeniero cloud",
        "ingeniera cloud",
        "ingeniero de redes",
        "ingeniera de redes",
        "administrador de redes",
        "administradora de redes",
        "analista de seguridad",
        "ingeniero de seguridad",
        "ingeniera de seguridad",
        "diseñador ux",
        "diseñadora ux",
        "diseñador ui",
        "diseñadora ui",
        "diseñador ux/ui",
        "diseñadora ux/ui",
        "diseñador de producto",
        "diseñadora de producto",
        "diseñador de interacción",
        "diseñadora de interacción",
        "diseñador visual",
        "diseñadora visual",
        # Roles generales - Inglés
        "developer",
        "programmer",
        "software developer",
        "software engineer",
        "web developer",
        "full stack",
        "full-stack",
        # Data & Analytics
        "systems analyst",
        "bi analyst",
        "bi developer",
        # Sysadmin & DevOps
        "system administrator",
        "infrastructure engineer",
        # QA & Testing
        "qa engineer",
        "quality assurance",
        "qa analyst",
        "qa tester",
        "test automation",
        "automation engineer",
        # Seguridad
        "cybersecurity",
        "ciberseguridad",
        "pentester",
        "soc analyst",
        "infosec",
        "seguridad informática",
        "seguridad informatica",
        "information security",
        "cybersecurity analyst",
        "penetration tester",
        "security engineer",
        # Soporte
        "soporte técnico",
        "soporte técnico informático",
        "soporte tecnico informatico",
        "soporte técnico it",
        "soporte tecnico it",
        "soporte it",
        "support engineer",
        "it support specialist",
        "technical support specialist",
        "help desk technician",
        "service desk analyst",
        "desktop support",
        # UX/UI
        "user experience",
        "experiencia de usuario",
        "user interface",
        "interfaz de usuario",
        "ux research",
        "investigación ux",
        "ui developer",
        "frontend designer",
        "usability",
        "usabilidad",
        "prototyping",
        "prototipado",
        "wireframing",
        "wireframes",
        "user research",
        "investigación de usuarios",
        "design system",
        "sistema de diseño",
        "ux researcher",
        "interaction designer",
        "visual designer",
        # Redes
        "network analyst",
        "analista de redes",
        "redes informáticas",
        "redes informaticas",
        "administración de redes",
        "administracion de redes",
        "network administration",
        "infraestructura de red",
        "network infrastructure",
        "network engineer",
        "network administrator",
        "network operations",
        "operaciones de red",
        # Tecnologías adicionales
        "sqlserver",
        "puppet",
        "travis",
        "cisco",
        "firewall",
        "cortafuegos",
        "vpn",
        "ids",
        "ips",
        "html",
        "css",
        "sass",
        "less",
        "linux",
        "unix",
        "windows server",
        # Sistemas Operativos
        "sistemas operativos",
        "operating systems",
        "sistema operativo windows",
        "sistema operativo linux",
        "linux server",
        "windows administration",
        "administración de windows",
        # Conceptos
        "etl",
        "data warehouse",
        "almacén de datos",
        "data pipeline",
        "pipeline de datos",
        "data modeling",
        "modelado de datos",
        "cloud computing",
        "computación en la nube",
        "api gateway",
        "microservices",
        "microservicios",
        "containers",
        "contenedores",
        "test-driven development",
        "integración continua",
        "continuous integration",
        "continuous deployment",
        "despliegue continuo",
        # Roles específicos
        "tester",
        "desarrollador frontend",
        "desarrollador backend",
        "desarrollador fullstack",
        "desarrollador mobile",
        "desarrollador ios",
        "desarrollador android",
        "data science",
        "sysadmin",
        "backend engineer",
        "frontend engineer",
        "fullstack developer",
        "mobile developer",
        "ios developer",
        "android developer",
        "qa engineer",
        "cloud engineer",
        "site reliability engineer",
        "ml engineer",
        "ai engineer",
        "platform engineer",
        "business intelligence",
        "analytics engineer",
        "big data engineer",
        # Lenguajes adicionales
        "c++",
        "ruby",
        "php",
        "scala",
        "haskell",
        "perl",
        "shell",
        "bash",
        "powershell",
        "dart",
        "elixir",
        "clojure",
        "lua",
        "matlab",
        "r language",
        "r programming",
        # Frameworks adicionales
        "nextjs",
        "spring boot",
        "expressjs",
        "express.js",
        "nestjs",
        "svelte",
        "ember",
        "symfony",
        "rails",
        "asp.net",
        "blazor",
        # Data tools
        "numpy",
        "looker",
        "pyspark",
        "aprendizaje automático",
        "tensorflow",
        "pytorch",
        "scikit-learn",
        "sklearn",
        "hadoop",
        "hive",
        "superset",
        "mlops",
        "databricks",
        "master data",
        "mdm",
        # Design tools
        "invision",
        "zeplin",
        "framer",
        # Cloud & DevOps
        "google cloud",
        "git",
        "github",
        "gitlab",
        "bitbucket",
        "circleci",
        "gitlab ci",
        "github actions",
        "helm",
        "vault",
        "openshift",
        "cloudformation",
        "pulumi",
        "ftth",
        # Databases
        "oracle",
        "mssql",
        "sql server",
        "cassandra",
        "dynamodb",
        "neo4j",
        "mariadb",
        "sqlite",
        "firestore",
        # API & Architecture
        "rest",
        "restful",
        "graphql",
        "api",
        "tdd",
        "bdd",
        "devsecops",
        # Soporte específico
        "incidencias",
        "ticket",
        "tickets",
        "ticketing",
        "zoho",
        "chatbot",
        "help desk",
        "service desk",
        "mesa de ayuda",
        # Active Directory
        "active directory",
        "controlador de dominio",
        "domain controller",
        "azure ad",
        "entra id",
        # Cloud storage IT
        "administración de onedrive",
        "administracion de onedrive",
        "sharepoint administration",
        "administración de sharepoint",
        # Gestión IT
        "gestión de inventario it",
        "gestión de inventario ti",
        "it inventory management",
        "gestión de activos it",
        "it asset management",
        "sistema de tickets",
        "ticketing system",
        "gestión de incidencias it",
        "it incident management",
        "resolución de incidentes",
        "incident resolution",
        "firewall configuration",
        "configuración de firewall",
        "redes LAN",
        "lan networks",
        "redes WAN",
        "wan networks",
        "monitorización de redes",
        "network monitoring",
        "backup and recovery",
        "respaldo y recuperación",
        "disaster recovery",
        "recuperación ante desastres",
        "virtualización de servidores",
        "server virtualization",
        "hyper-v",
        "vmware",
        # Hardware IT
        "mantenimiento de equipos informáticos",
        "mantenimiento de equipos informaticos",
        "computer hardware maintenance",
        "instalación de hardware",
        "hardware installation",
    ]
)

# Eliminar señales débiles de la lista de señales requeridas
REQUIRED_IT_SIGNALS = [s for s in REQUIRED_IT_SIGNALS if s not in WEAK_IT_SIGNALS]

# Eliminar duplicados manteniendo orden
REQUIRED_IT_SIGNALS = list(dict.fromkeys(REQUIRED_IT_SIGNALS))
