TAGS_KEYWORDS = {
    "roles": [
        {
            "search_terms": ["frontend", "desarrollador frontend"],
            "display_tag": "frontend",
        },
        {
            "search_terms": ["backend", "desarrollador backend"],
            "display_tag": "backend",
        },
        {
            "search_terms": ["fullstack", "desarrollador fullstack"],
            "display_tag": "fullstack",
        },
        {
            "search_terms": ["mobile", "desarrollador mobile", "desarrollador móvil"],
            "display_tag": "mobile",
        },
        {"search_terms": ["devops"], "display_tag": "devops"},
        {
            "search_terms": ["qa", "quality assurance", "analista de calidad"],
            "display_tag": "qa",
        },
        {
            "search_terms": ["data scientist", "científico de datos"],
            "display_tag": "científico de datos",
        },
        {
            "search_terms": ["data engineer", "ingeniero de datos"],
            "display_tag": "ingeniero de datos",
        },
        {
            "search_terms": ["data analyst", "analista de datos"],
            "display_tag": "analista de datos",
        },
        {"search_terms": ["sre", "site reliability engineer"], "display_tag": "sre"},
        {"search_terms": ["ux/ui", "diseñador ux/ui"], "display_tag": "ux/ui"},
        {
            "search_terms": ["product design", "diseño de producto"],
            "display_tag": "diseño de producto",
        },
        {
            "search_terms": ["cloud engineer", "ingeniero de nube", "ingeniero cloud"],
            "display_tag": "cloud",
        },
        {
            "search_terms": ["cybersecurity", "ciberseguridad"],
            "display_tag": "ciberseguridad",
        },
        {
            "search_terms": ["sysadmin", "administrador de sistemas"],
            "display_tag": "sysadmin",
        },
        {
            "search_terms": ["game developer", "desarrollador de videojuegos"],
            "display_tag": "desarrollador de videojuegos",
        },
        {
            "search_terms": ["product manager", "gerente de producto"],
            "display_tag": "product manager",
        },
        {"search_terms": ["scrum master"], "display_tag": "scrum master"},
    ],
    "languages": [
        {"search_terms": ["python"], "display_tag": "python"},
        {"search_terms": ["javascript"], "display_tag": "javascript"},
        {"search_terms": ["typescript"], "display_tag": "typescript"},
        {"search_terms": ["java"], "display_tag": "java"},
        {"search_terms": ["golang"], "display_tag": "golang"},
        {"search_terms": ["c#", "c sharp"], "display_tag": "c#"},
        {"search_terms": ["kotlin"], "display_tag": "kotlin"},
        {"search_terms": ["swift"], "display_tag": "swift"},
        {"search_terms": ["rust"], "display_tag": "rust"},
        {"search_terms": ["sql"], "display_tag": "sql"},
        {"search_terms": ["php"], "display_tag": "php"},
        {"search_terms": ["c++", "cpp"], "display_tag": "c++"},
        {"search_terms": ["ruby"], "display_tag": "ruby"},
        {"search_terms": ["dart"], "display_tag": "dart"},
        {"search_terms": ["scala"], "display_tag": "scala"},
        {"search_terms": ["powershell"], "display_tag": "powershell"},
        {"search_terms": ["bash"], "display_tag": "bash"},
    ],
    "technologies": [
        {"search_terms": ["react", "react.js", "reactjs"], "display_tag": "react"},
        {"search_terms": ["node.js", "nodejs"], "display_tag": "node.js"},
        {"search_terms": ["next.js", "nextjs"], "display_tag": "next.js"},
        {"search_terms": ["svelte"], "display_tag": "svelte"},
        {"search_terms": ["nest.js", "nestjs", "nest"], "display_tag": "nest.js"},
        {"search_terms": ["vue", "vue.js"], "display_tag": "vue"},
        {"search_terms": ["angular"], "display_tag": "angular"},
        {"search_terms": ["django"], "display_tag": "django"},
        {"search_terms": ["flask"], "display_tag": "flask"},
        {"search_terms": ["fastapi"], "display_tag": "fastapi"},
        {"search_terms": ["spring", "spring boot"], "display_tag": "spring"},
        {"search_terms": ["react native"], "display_tag": "react native"},
        {"search_terms": ["flutter"], "display_tag": "flutter"},
        {
            "search_terms": ["machine learning", "aprendizaje automático"],
            "display_tag": "aprendizaje automático",
        },
        {"search_terms": ["pandas"], "display_tag": "pandas"},
        {"search_terms": ["spark", "apache spark"], "display_tag": "spark"},
        {"search_terms": ["power bi"], "display_tag": "power bi"},
        {"search_terms": ["tableau"], "display_tag": "tableau"},
        {"search_terms": ["airflow", "apache airflow"], "display_tag": "airflow"},
        {"search_terms": ["kafka", "apache kafka"], "display_tag": "kafka"},
        {"search_terms": ["figma"], "display_tag": "figma"},
        {"search_terms": ["sketch"], "display_tag": "sketch"},
        {"search_terms": ["adobe xd"], "display_tag": "adobe xd"},
        {"search_terms": ["aws", "amazon web services"], "display_tag": "aws"},
        {"search_terms": ["azure", "microsoft azure"], "display_tag": "azure"},
        {"search_terms": ["gcp", "google cloud platform"], "display_tag": "gcp"},
        {"search_terms": ["docker"], "display_tag": "docker"},
        {"search_terms": ["kubernetes", "k8s"], "display_tag": "kubernetes"},
        {"search_terms": ["terraform"], "display_tag": "terraform"},
        {
            "search_terms": [
                "ci/cd",
                "continuous integration",
                "continuous delivery",
                "integración continua",
                "entrega continua",
            ],
            "display_tag": "ci/cd",
        },
        {"search_terms": ["postgres", "postgresql"], "display_tag": "postgres"},
        {"search_terms": ["mysql"], "display_tag": "mysql"},
        {"search_terms": ["mongodb"], "display_tag": "mongodb"},
        {"search_terms": ["redis"], "display_tag": "redis"},
        {"search_terms": ["elasticsearch"], "display_tag": "elasticsearch"},
        {"search_terms": ["agile", "metodologías ágiles"], "display_tag": "agile"},
        {"search_terms": ["scrum"], "display_tag": "scrum"},
        {"search_terms": ["kanban"], "display_tag": "kanban"},
        {
            "search_terms": ["microservices", "microservicios"],
            "display_tag": "microservicios",
        },
        {"search_terms": [".net"], "display_tag": ".net"},
        {"search_terms": ["laravel"], "display_tag": "laravel"},
        {"search_terms": ["jenkins"], "display_tag": "jenkins"},
        {
            "search_terms": ["sql server", "microsoft sql server"],
            "display_tag": "sql server",
        },
        {"search_terms": ["ios"], "display_tag": "ios"},
        {"search_terms": ["android"], "display_tag": "android"},
        {"search_terms": ["unity"], "display_tag": "unity"},
        {"search_terms": ["unreal engine"], "display_tag": "unreal engine"},
        {"search_terms": ["git"], "display_tag": "git"},
        {"search_terms": ["selenium"], "display_tag": "selenium"},
        {"search_terms": ["cypress"], "display_tag": "cypress"},
        {"search_terms": ["linux"], "display_tag": "linux"},
        {"search_terms": ["windows server"], "display_tag": "windows server"},
        {"search_terms": ["graphql"], "display_tag": "graphql"},
        {"search_terms": ["rest api", "api rest"], "display_tag": "rest api"},
    ],
}
