TAGS_KEYWORDS = {
    "roles": [
        "frontend",
        "backend",
        "fullstack",
        "mobile",
        "devops",
        "qa",
        "data scientist",
        "data engineer",
        "data analyst",
        "sre",
        "ux/ui",
        "product design",
        "cloud engineer",
        "cybersecurity",
        "sysadmin",
        "game developer",
    ],
    "languages": [
        "python",
        "javascript",
        "typescript",
        "java",
        "golang",
        "c#",
        "kotlin",
        "swift",
        "rust",
        "sql",
        "php",
        "c++",
        "ruby",
        "dart",
    ],
    "technologies": [
        "react",
        "node.js",
        "next.js",
        "vue",
        "angular",
        "django",
        "flask",
        "fastapi",
        "spring",
        "react native",
        "flutter",
        "machine learning",
        "pandas",
        "spark",
        "power bi",
        "tableau",
        "airflow",
        "kafka",
        "figma",
        "sketch",
        "adobe xd",
        "aws",
        "azure",
        "gcp",
        "docker",
        "kubernetes",
        "terraform",
        "ci/cd",
        "postgres",
        "mysql",
        "mongodb",
        "redis",
        "elasticsearch",
        "agile",
        "scrum",
        "kanban",
        "microservices",
        ".net",
        "laravel",
        "jenkins",
        "sql server",
        "ios",
        "android",
        "unity",
    ],
}
