name: Job Alert Bot

on:
  schedule:
    # Lunes a Viernes: 9, 11, 13, 15, 17, 19 ART y 00:00 ART del día siguiente
    - cron: "0 3,12,14,16,18,20,22 * * 1-5"

    # Sábados y Domingos: 9:00, 21:00 ART
    - cron: "0 0,12 * * 6,0"

  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
      REVALIDATION_SECRET: ${{ secrets.REVALIDATION_SECRET }}
      BASE_URL: ${{ secrets.BASE_URL }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure Google credentials
        run: |
          echo "${{ secrets.FIREBASE_CREDENTIALS_BASE64 }}" | base64 --decode > /tmp/credentials.json

      - name: Run Job Alert Bot
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/credentials.json
        run: python main.py
