name: Job Alert Bot

on:
  schedule:
    - cron: "0 */6 * * *" # Cada 6 horas
  workflow_dispatch: # Permite ejecución manual

jobs:
  run-bot:
    runs-on: ubuntu-latest
    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download previous jobs.json
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: jobs_json
          path: .

      - name: Ensure jobs.json exists
        run: |
          if [ ! -f jobs.json ]; then
            echo "[]" > jobs.json
          fi

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Job Alert Bot
        run: python bot.py

      - name: Upload updated jobs.json
        uses: actions/upload-artifact@v4
        with:
          name: jobs_json
          path: jobs.json
